"""Многоязычный лексикон понятий, связанных с угрозами.

Формат термина:

* ``"слово"`` — точное слово (для языков с пробелами — с границами слова);
* ``"основа*"`` — основа с любым окончанием (существительные, прочее);
* ``"основа+"`` — глагольная основа агглютинативного языка: форма (намерение,
  призыв) и отрицание определяются по аффиксу (см. ``SUFFIX_FORMS``);
* ``"re:..."`` — регулярное выражение по нормализованному тексту;
* фразы через пробел; для zh/ja/ko/ar/fa сопоставление идёт по подстроке.

Формы: ``b`` — нейтральная (инфинитив, существительное), ``f`` — намерение
1-го лица / будущее время («убью», «o'ldiraman», «سأقتل»), ``i`` —
повелительное наклонение / призыв («убейте», «o'ldiring», «اقتلوا»).

Латинские и кириллические варианты (транслит, узбекская двойная графика,
неформальные написания) генерируются автоматически в ``lexicon.py``.

ВАЖНО: это стартовый лексикон. Перед промышленным применением его должны
проверить и дополнить носители языков и предметные эксперты; дополнения
подключаются файлом ``DOZOR_LEXICON_EXTRA`` (JSON того же формата).
"""

# group: роль понятия в классификаторе
#   violence     — насильственное действие
#   weapon       — оружие (признак подготовки/тяжести)
#   recruit      — вербовочный призыв / логистика
#   ideology     — идеологический контекст (сам по себе НЕ признак угрозы)
#   contact      — канал связи («пиши в лс», бот)
#   harass       — травля (самоповреждение, деанон, массовая атака, оскорбления)
#   dehumanize   — расчеловечивание
#   expel        — призывы к изгнанию
#   involve      — опасное вовлечение (оплачиваемые «задания», несовершеннолетние)
#   warning      — тревожные поведенческие признаки в тексте (по мотивам TRAP-18)
# severity: catastrophic | severe | significant | moderate | context

CONCEPTS: dict[str, dict] = {
    # ------------------------------------------------------------------ НАСИЛИЕ
    "kill": {
        "label": "убийство",
        "group": "violence",
        "severity": "severe",
        "terms": {
            "ru": {
                "b": ["убить", "убивать", "убийство", "убийства", "прикончить", "замочить", "грохнуть", "порешить", "ликвидировать"],
                "f": ["убью", "убьём", "убьем", "убьет", "убьют", "прикончу", "замочу", "грохну", "порешу", "уничтожу", "уничтожим", "убьемся"],
                "i": ["убей", "убейте", "убивай", "убивайте", "мочите", "прикончите", "кончайте их"],
            },
            "en": {
                "b": ["kill", "killing", "killed", "murder*", "slaughter*", "unalive"],
                "f": ["i will kill", "i'll kill", "i'm going to kill", "im going to kill", "gonna kill", "we will kill", "we'll kill", "i will murder"],
                "i": ["kill them", "kill all", "kill him", "kill her", "kill every*", "murder them"],
            },
            "fr": {
                "b": ["tuer", "assassiner", "massacrer", "buter", "flinguer"],
                "f": ["tuerai", "tuerons", "vais tuer", "vais te tuer", "vais les tuer", "vais vous tuer", "buterai", "vais te buter"],
                "i": ["tuez", "tuons", "tuez-les", "butez-les"],
            },
            "de": {
                "b": ["töten", "umbringen", "ermorden", "abschlachten", "killen"],
                "f": ["werde töten", "werde dich töten", "ich bring dich um", "ich bringe dich um", "bringe euch um", "mach dich kalt", "werde euch töten"],
                "i": ["tötet", "tötet sie", "bringt sie um", "bringt alle um"],
            },
            "es": {
                "b": ["matar", "asesinar", "masacrar", "liquidar"],
                "f": ["mataré", "mataremos", "voy a matar", "te voy a matar", "los voy a matar", "te mato", "vamos a matar"],
                "i": ["maten", "matadlos", "mátenlos", "matemos"],
            },
            "it": {
                "b": ["uccidere", "ammazzare", "massacrare", "fare fuori"],
                "f": ["ucciderò", "ammazzerò", "ti ammazzo", "vi ammazzo", "ti uccido", "vi uccido"],
                "i": ["uccidete", "ammazzate", "uccidiamoli", "ammazzateli"],
            },
            "ko": {
                "b": ["죽이다", "살해", "죽이는"],
                "f": ["죽일 거야", "죽일거", "죽여버릴", "죽여 버릴", "죽이겠다", "죽여 버리겠", "죽인다"],
                "i": ["죽여라", "죽이자", "죽여버려"],
            },
            "ja": {
                "b": ["殺す", "殺害", "殺し"],
                "f": ["殺してやる", "ぶっ殺す", "殺すつもり", "殺します", "全員殺す", "殺すから", "re:殺す(?=[。！!]|$)"],
                "i": ["殺せ", "殺しましょう", "殺そう"],
            },
            "zh": {
                "b": ["杀死", "杀掉", "谋杀", "杀人"],
                "f": ["我要杀", "我会杀", "我要弄死", "弄死你", "杀了你", "我们要杀"],
                "i": ["杀光", "杀了他们", "去杀", "杀死他们"],
            },
            "fa": {
                "b": ["قتل", "کشتن", "کشتار"],
                "f": ["میکشمت", "خواهم کشت", "میکشمتون", "میکشیمشان", "میکشمش"],
                "i": ["بکشیدشان", "بکشیدش", "باید کشت", "باید کشته شوند"],
            },
            "ar": {
                "b": ["قتل", "اغتيال"],
                "f": ["سأقتل", "سنقتل", "سوف أقتل", "سأقتلك", "سنقتلكم"],
                "i": ["اقتلوا", "اقتلوهم"],
            },
            "uz": {
                "b": ["o'ldir+", "qotillik"],
                "f": ["o'ldiraman", "o'ldiramiz", "o'ldirib qo'yaman"],
                "i": ["o'ldiring", "o'ldiringlar", "o'ldir"],
            },
            "kk": {
                "b": ["өлтір+", "кісі өлтіру"],
                "f": ["өлтіремін", "өлтіреміз"],
                "i": ["өлтіріңдер", "өлтіріңіз", "өлтір"],
            },
            "ky": {
                "b": ["өлтүр+"],
                "f": ["өлтүрөм", "өлтүрөбүз"],
                "i": ["өлтүргүлө", "өлтүрүңүз", "өлтүр"],
            },
            "tg": {
                "b": ["куштан", "кушт*", "қатл"],
                "f": ["мекушам", "мекушем", "мекушамат", "мекушамаш"],
                "i": ["кушед", "бикушед", "бикуш"],
            },
            "tk": {
                "b": ["öldür+"],
                "f": ["öldürerin", "öldürjek", "öldürjekdirin"],
                "i": ["öldüriň", "öldüriňler"],
            },
            "tr": {
                "b": ["öldür+", "katlet+"],
                "f": ["öldüreceğim", "öldüreceğiz", "seni öldürürüm"],
                "i": ["öldürün"],
            },
        },
    },
    "explode": {
        "label": "взрыв / подрыв",
        "group": "violence",
        "severity": "catastrophic",
        "terms": {
            "ru": {
                "b": ["взорвать", "взрыв", "взрывать", "бомба", "бомбу", "бомбой", "взрывчатк*", "взрывное устройство", "сву", "тротил", "пояс шахида", "подорвать"],
                "f": ["взорву", "взорвём", "взорвем", "подорву", "подорвём", "подорвем"],
                "i": ["взорвите", "взрывайте", "подорвите"],
            },
            "en": {
                "b": ["bomb", "bombing", "blow up", "explosive*", "ied", "detonate", "suicide vest", "pipe bomb"],
                "f": ["i will blow up", "i'll blow up", "gonna blow up", "going to blow up", "i will bomb", "i'll bomb"],
                "i": ["blow them up", "bomb them", "blow it up"],
            },
            "fr": {
                "b": ["bombe", "explosif*", "faire exploser", "ceinture explosive"],
                "f": ["vais faire exploser", "ferai exploser", "vais tout faire sauter"],
                "i": ["faites exploser", "faites sauter"],
            },
            "de": {
                "b": ["bombe", "sprengstoff", "sprengen", "in die luft jagen", "sprengsatz"],
                "f": ["werde sprengen", "jage in die luft", "werde in die luft jagen"],
                "i": ["sprengt", "jagt sie in die luft"],
            },
            "es": {
                "b": ["bomba", "explosivo*", "hacer estallar", "volar por los aires", "detonar"],
                "f": ["voy a volar", "haré estallar", "voy a hacer estallar"],
                "i": ["vuélenlo", "hagan estallar"],
            },
            "it": {
                "b": ["bomba", "esplosiv*", "far saltare", "far esplodere", "ordigno"],
                "f": ["farò saltare", "faccio saltare", "farò esplodere"],
                "i": ["fate saltare", "fate esplodere"],
            },
            "ko": {
                "b": ["폭탄", "폭파", "폭발물", "사제폭탄"],
                "f": ["폭파할 거야", "폭파하겠다", "터뜨릴 거야", "폭파할거"],
                "i": ["폭파해라", "터뜨려라"],
            },
            "ja": {
                "b": ["爆弾", "爆破", "爆発物", "自爆"],
                "f": ["爆破してやる", "爆破する", "爆破します"],
                "i": ["爆破しろ"],
            },
            "zh": {
                "b": ["炸弹", "爆炸物", "炸掉", "引爆", "自杀式袭击"],
                "f": ["我要炸", "我会炸", "炸了你", "我要引爆"],
                "i": ["炸死他们", "炸掉它"],
            },
            "fa": {
                "b": ["بمب", "مواد منفجره", "منفجر کردن", "انفجار"],
                "f": ["منفجر میکنم", "منفجرش میکنم", "منفجر خواهم کرد"],
                "i": ["منفجر کنید"],
            },
            "ar": {
                "b": ["قنبلة", "متفجرات", "تفجير", "عبوة ناسفة", "حزام ناسف"],
                "f": ["سأفجر", "سنفجر"],
                "i": ["فجروا"],
            },
            "uz": {
                "b": ["portlat+", "portlovchi", "bomba", "bombani"],
                "f": ["portlataman", "portlatamiz"],
                "i": ["portlating", "portlatinglar"],
            },
            "kk": {
                "b": ["жарып жіберу", "жарылғыш", "бомба", "жарылыс"],
                "f": ["жарып жіберемін", "жарамын", "жарып жібереміз"],
                "i": ["жарып жіберіңдер"],
            },
            "ky": {
                "b": ["жардыр+", "жарылуучу", "бомба", "жарылуу"],
                "f": ["жардырам", "жардырабыз"],
                "i": ["жардыргыла"],
            },
            "tg": {
                "b": ["тарконидан", "таркиш", "маводи тарканда", "бомба"],
                "f": ["метарконам", "метарконем"],
                "i": ["тарконед"],
            },
            "tk": {
                "b": ["partlat+", "partlaýjy", "bomba"],
                "f": ["partladaryn", "partlatjak"],
                "i": ["partladyň"],
            },
            "tr": {
                "b": ["bomba", "patlat+", "patlayıcı", "canlı bomba"],
                "f": ["patlatacağım", "patlatacağız"],
                "i": ["patlatın"],
            },
        },
    },
    "shoot": {
        "label": "стрельба",
        "group": "violence",
        "severity": "severe",
        "terms": {
            "ru": {
                "b": ["застрелить", "расстрелять", "расстрел", "стрельба", "стрельбу", "стрелять", "перестрелять", "пристрелить"],
                "f": ["застрелю", "расстреляю", "перестреляю", "пристрелю", "расстреляем", "перестреляем"],
                "i": ["стреляйте", "расстреляйте", "застрелите"],
            },
            "en": {
                "b": ["shoot", "shooting", "shot dead", "gun down", "mass shooting", "open fire"],
                "f": ["i will shoot", "i'll shoot", "i'm going to shoot", "im going to shoot", "gonna shoot", "we will shoot"],
                "i": ["shoot them", "shoot him", "shoot her", "shoot every*"],
            },
            "fr": {
                "b": ["tirer sur", "fusiller", "fusillade", "abattre"],
                "f": ["vais tirer", "vais vous abattre", "abattrai", "vais te tirer dessus"],
                "i": ["tirez sur", "abattez"],
            },
            "de": {
                "b": ["erschießen", "schießen", "schießerei", "niederschießen", "amoklauf"],
                "f": ["werde erschießen", "erschieße dich", "knalle euch ab", "knall dich ab"],
                "i": ["erschießt", "schießt auf"],
            },
            "es": {
                "b": ["disparar", "fusilar", "tiroteo", "balacera", "acribillar"],
                "f": ["voy a disparar", "te voy a disparar", "dispararé", "te voy a pegar un tiro"],
                "i": ["disparen", "fusílenlos"],
            },
            "it": {
                "b": ["sparare", "fucilare", "sparatoria"],
                "f": ["vi sparo", "ti sparo", "sparerò"],
                "i": ["sparate", "fucilateli"],
            },
            "ko": {
                "b": ["총격", "총기 난사", "쏴 죽", "사살"],
                "f": ["쏴 죽일", "쏘겠다", "쏴버릴"],
                "i": ["쏴라", "쏴 죽여"],
            },
            "ja": {
                "b": ["射殺", "銃撃", "乱射", "撃ち殺"],
                "f": ["撃ち殺してやる", "撃ってやる"],
                "i": ["撃て", "撃ち殺せ"],
            },
            "zh": {
                "b": ["枪杀", "开枪", "枪击", "扫射"],
                "f": ["我要开枪", "我会开枪", "一枪崩了"],
                "i": ["开枪打死", "打死他们"],
            },
            "fa": {
                "b": ["تیراندازی", "شلیک", "به رگبار بستن"],
                "f": ["شلیک میکنم", "به رگبار میبندم"],
                "i": ["شلیک کنید"],
            },
            "ar": {
                "b": ["إطلاق النار", "اطلاق نار", "الرصاص"],
                "f": ["سأطلق النار", "سنطلق النار"],
                "i": ["أطلقوا النار"],
            },
            "uz": {
                "b": ["otib tashla+", "otib o'ldir+", "o'q uz+", "otishma"],
                "f": ["otib tashlayman", "o'q uzaman", "otib o'ldiraman"],
                "i": ["otib tashlang", "otinglar"],
            },
            "kk": {
                "b": ["атып тастау", "атып өлтір+", "атыс"],
                "f": ["атып тастаймын", "атып өлтіремін"],
                "i": ["атып тастаңдар", "атыңдар"],
            },
            "ky": {
                "b": ["атып салуу", "атып өлтүр+", "атышуу"],
                "f": ["атып салам", "атып өлтүрөм"],
                "i": ["аткыла", "атып салгыла"],
            },
            "tg": {
                "b": ["тирандозӣ", "тирборон"],
                "f": ["тир мезанам"],
                "i": ["тир занед"],
            },
            "tk": {
                "b": ["atyp öldür+", "atyşyk"],
                "f": ["atyp öldürerin"],
                "i": ["atyň"],
            },
            "tr": {
                "b": ["kurşunla+", "kurşuna diz+", "silahlı saldırı", "ateş aç+"],
                "f": ["kurşunlayacağım", "ateş açacağım", "vuracağım"],
                "i": ["kurşunlayın", "ateş açın"],
            },
        },
    },
    "stab": {
        "label": "нападение с ножом / обезглавливание",
        "group": "violence",
        "severity": "severe",
        "terms": {
            "ru": {
                "b": ["зарезать", "прирезать", "заколоть", "поножовщин*", "перерезать горло", "отрезать голову", "обезглавить"],
                "f": ["зарежу", "прирежу", "заколю", "порежу", "зарежем"],
                "i": ["режьте", "зарежьте"],
            },
            "en": {
                "b": ["stab", "stabbing", "behead*", "slit his throat", "slit her throat", "slit their throat*", "cut his throat"],
                "f": ["i'll stab", "i will stab", "gonna stab", "going to stab"],
                "i": ["stab them", "behead them"],
            },
            "fr": {
                "b": ["poignarder", "égorger", "décapiter"],
                "f": ["vais te poignarder", "vais égorger", "égorgerai"],
                "i": ["égorgez", "poignardez"],
            },
            "de": {
                "b": ["erstechen", "abstechen", "köpfen", "enthaupten", "messerangriff"],
                "f": ["stech dich ab", "steche dich ab", "werde abstechen"],
                "i": ["stecht sie ab"],
            },
            "es": {
                "b": ["apuñalar", "degollar", "decapitar", "acuchillar"],
                "f": ["te voy a apuñalar", "te apuñalo"],
                "i": ["degüéllenlos"],
            },
            "it": {
                "b": ["accoltellare", "sgozzare", "decapitare"],
                "f": ["ti accoltello", "ti sgozzo"],
                "i": ["sgozzateli"],
            },
            "ko": {
                "b": ["칼로 찌르", "찔러 죽", "흉기 난동", "목을 베"],
                "f": ["찔러 죽일", "찔러버릴"],
                "i": ["찔러라"],
            },
            "ja": {
                "b": ["刺し殺", "刺殺", "首を切", "斬首"],
                "f": ["刺してやる", "刺し殺してやる"],
                "i": ["刺せ"],
            },
            "zh": {
                "b": ["捅死", "砍死", "刺死", "砍头", "割喉"],
                "f": ["我要捅", "捅死你", "砍死你"],
                "i": ["砍死他们"],
            },
            "fa": {
                "b": ["چاقو زدن", "سر بریدن"],
                "f": ["چاقو میزنم", "سرت را میبرم"],
                "i": ["سرشان را ببرید", "سر ببرید"],
            },
            "ar": {
                "b": ["طعن", "ذبح", "قطع الرأس", "نحر"],
                "f": ["سأذبح", "سأطعن", "سنذبح"],
                "i": ["اذبحوا", "اذبحوهم"],
            },
            "uz": {
                "b": ["pichoqla+", "boshini kes+"],
                "f": ["pichoqlayman", "boshingni kesaman"],
                "i": ["pichoqlang"],
            },
            "kk": {
                "b": ["пышақта+", "басын кес+", "бауызда+"],
                "f": ["бауыздаймын", "пышақтаймын"],
                "i": ["бауыздаңдар"],
            },
            "ky": {
                "b": ["бычакта+", "мууздоо", "башын кес+"],
                "f": ["мууздайм", "бычактайм"],
                "i": ["мууздагыла"],
            },
            "tg": {
                "b": ["корд задан", "сар буридан"],
                "f": ["сарашро мебурам", "корд мезанам"],
                "i": ["сарашонро буред"],
            },
            "tk": {
                "b": ["pyçakla+", "kellesini kes+"],
                "f": ["pyçaklaryn"],
                "i": ["pyçaklaň"],
            },
            "tr": {
                "b": ["bıçakla+", "kafasını kes+", "boğazını kes+"],
                "f": ["bıçaklayacağım", "kafanı keseceğim"],
                "i": ["bıçaklayın"],
            },
        },
    },
    "burn": {
        "label": "поджог",
        "group": "violence",
        "severity": "significant",
        "terms": {
            "ru": {
                "b": ["сжечь", "поджечь", "поджог", "спалить", "сжечь заживо", "подпалить"],
                "f": ["сожгу", "подожгу", "спалю", "сожжём", "сожжем", "подожжём", "подожжем"],
                "i": ["сожгите", "поджигайте", "подожгите", "жгите"],
            },
            "en": {
                "b": ["burn down", "burn alive", "set fire", "set on fire", "arson", "firebomb"],
                "f": ["i'll burn", "i will burn", "gonna burn"],
                "i": ["burn it down", "burn them"],
            },
            "fr": {
                "b": ["brûler", "incendier", "mettre le feu", "brûler vif"],
                "f": ["brûlerai", "vais brûler", "vais mettre le feu"],
                "i": ["brûlez", "mettez le feu"],
            },
            "de": {
                "b": ["niederbrennen", "anzünden", "abfackeln", "brandanschlag"],
                "f": ["werde anzünden", "zünde an", "fackel ab"],
                "i": ["zündet an", "fackelt ab"],
            },
            "es": {
                "b": ["quemar", "incendiar", "prender fuego", "quemar vivo"],
                "f": ["quemaré", "voy a quemar"],
                "i": ["quemen", "incendien"],
            },
            "it": {
                "b": ["bruciare", "incendiare", "dare fuoco", "bruciare vivo"],
                "f": ["brucerò", "do fuoco"],
                "i": ["bruciate", "date fuoco"],
            },
            "ko": {"b": ["불태우", "방화", "불을 지르", "불 질러"], "f": ["불태워 버릴", "불을 지르겠다"], "i": ["불태워라", "불 질러라"]},
            "ja": {"b": ["燃やす", "放火", "火をつけ", "焼き殺"], "f": ["燃やしてやる", "放火してやる"], "i": ["燃やせ", "火をつけろ"]},
            "zh": {"b": ["烧掉", "纵火", "放火", "烧死"], "f": ["我要烧", "我要放火"], "i": ["烧死他们", "烧了它"]},
            "fa": {"b": ["آتش زدن", "به آتش کشیدن", "سوزاندن"], "f": ["آتش میزنم", "به آتش میکشم"], "i": ["آتش بزنید"]},
            "ar": {"b": ["حرق", "إحراق", "إضرام النار"], "f": ["سأحرق", "سنحرق"], "i": ["احرقوا"]},
            "uz": {"b": ["yoqib yubor+", "o't qo'y+", "yondir+"], "f": ["yoqib yuboraman", "o't qo'yaman"], "i": ["yoqib yuboring", "o't qo'ying"]},
            "kk": {"b": ["өрте+", "өртеп жіберу"], "f": ["өртеймін", "өртеп жіберемін"], "i": ["өртеңдер"]},
            "ky": {"b": ["өрттө+"], "f": ["өрттөйм"], "i": ["өрттөгүлө"]},
            "tg": {"b": ["сӯзон*", "оташ задан"], "f": ["месӯзонам", "оташ мезанам"], "i": ["сӯзонед", "оташ занед"]},
            "tk": {"b": ["ot ber+", "otla+"], "f": ["ot bererin"], "i": ["ot beriň"]},
            "tr": {"b": ["kundakla+", "ateşe ver+", "diri diri yak+"], "f": ["ateşe vereceğim", "yakacağım"], "i": ["ateşe verin"]},
        },
    },
    "attack": {
        "label": "теракт / нападение",
        "group": "violence",
        "severity": "catastrophic",
        "terms": {
            "ru": {
                "b": ["теракт*", "терракт*", "террористический акт", "нападение", "напасть", "атаковать", "бойня", "бойню", "массовое убийство", "резня", "резню"],
                "f": ["нападу", "нападём", "нападем", "атакую", "устрою теракт", "устроим теракт", "устрою бойню", "устроим резню"],
                "i": ["нападайте", "атакуйте", "нападите"],
            },
            "en": {
                "b": ["terror attack", "terrorist attack", "massacre", "rampage", "carnage", "attack"],
                "f": ["i will attack", "i'll attack", "we will attack", "gonna attack"],
                "i": ["attack them", "storm the"],
            },
            "fr": {"b": ["attentat", "attaque terroriste", "attaquer", "massacre", "tuerie"], "f": ["attaquerai", "vais attaquer"], "i": ["attaquez"]},
            "de": {"b": ["anschlag", "terroranschlag", "angreifen", "massaker", "blutbad"], "f": ["werde angreifen", "greife an"], "i": ["greift an"]},
            "es": {"b": ["atentado", "ataque terrorista", "atacar", "masacre", "matanza"], "f": ["atacaré", "voy a atacar"], "i": ["ataquen"]},
            "it": {"b": ["attentato", "attacco terroristico", "attaccare", "strage", "massacro"], "f": ["attaccherò"], "i": ["attaccate"]},
            "ko": {"b": ["테러", "습격", "학살", "무차별 공격"], "f": ["테러하겠다", "습격하겠다", "테러할 거야"], "i": ["공격하라", "습격하라"]},
            "ja": {"b": ["テロ", "襲撃", "虐殺", "無差別"], "f": ["テロを起こす", "襲撃してやる"], "i": ["襲撃しろ"]},
            "zh": {"b": ["恐怖袭击", "袭击", "屠杀", "血洗"], "f": ["我要袭击", "我要报复社会"], "i": ["袭击他们"]},
            "fa": {"b": ["حمله تروریستی", "عملیات تروریستی", "قتل عام", "حمله"], "f": ["حمله میکنم", "حمله خواهیم کرد"], "i": ["حمله کنید"]},
            "ar": {"b": ["هجوم", "عملية إرهابية", "هجوم إرهابي", "مجزرة", "غزوة", "عملية استشهادية"], "f": ["سنهاجم", "سأهاجم"], "i": ["هاجموا"]},
            "uz": {"b": ["terakt*", "hujum", "qirg'in", "qatli om"], "f": ["hujum qilaman", "hujum qilamiz", "terakt qilaman"], "i": ["hujum qiling", "hujum qilinglar"]},
            "kk": {"b": ["террорлық акт", "терракт", "теракт", "шабуыл", "қырғын"], "f": ["шабуыл жасаймын", "шабуылдаймын"], "i": ["шабуылдаңдар"]},
            "ky": {"b": ["террордук чабуул", "террордук акт", "теракт", "кол салуу", "чабуул", "кыргын"], "f": ["кол салам", "чабуул жасайм"], "i": ["кол салгыла"]},
            "tg": {"b": ["амали террористӣ", "ҳамлаи террористӣ", "ҳамла", "қатли ом", "теракт"], "f": ["ҳамла мекунам"], "i": ["ҳамла кунед"]},
            "tk": {"b": ["terrorçylykly hüjüm", "hüjüm", "gyrgyn"], "f": ["hüjüm ederin"], "i": ["hüjüm ediň"]},
            "tr": {"b": ["terör saldırısı", "saldırı", "katliam"], "f": ["saldıracağım", "saldırı yapacağım"], "i": ["saldırın"]},
        },
    },
    "beat": {
        "label": "избиение / причинение вреда",
        "group": "violence",
        "severity": "significant",
        "terms": {
            "ru": {"b": ["избить", "покалечить", "набить морду", "переломать"], "f": ["изобью", "покалечу", "переломаю", "урою", "изобьём", "изобьем"], "i": ["бейте", "избейте", "покалечьте"]},
            "en": {"b": ["beat up", "beat him to death", "beat her to death", "cripple"], "f": ["i'll beat you", "i will beat you up"], "i": ["beat them up"]},
            "fr": {"b": ["tabasser", "passer à tabac"], "f": ["vais te tabasser"], "i": ["tabassez"]},
            "de": {"b": ["verprügeln", "zusammenschlagen"], "f": ["werde dich verprügeln"], "i": ["verprügelt"]},
            "es": {"b": ["dar una paliza", "golpear hasta"], "f": ["te voy a dar una paliza"], "i": ["denle una paliza"]},
            "it": {"b": ["pestare", "massacrare di botte"], "f": ["ti pesto"], "i": ["pestatelo"]},
            "ko": {"b": ["패 죽이", "두들겨 패"], "f": ["패버릴"], "i": ["패라"]},
            "ja": {"b": ["殴り殺", "ボコボコにする"], "f": ["ボコボコにしてやる"], "i": ["殴れ"]},
            "zh": {"b": ["打死", "揍死"], "f": ["我要打死", "打死你"], "i": ["揍他"]},
            "fa": {"b": ["کتک زدن"], "f": ["کتکت میزنم"], "i": ["کتکش بزنید"]},
            "ar": {"b": ["ضرب حتى الموت"], "f": ["سأضربك"], "i": ["اضربوه"]},
            "uz": {"b": ["urib o'ldir+", "do'pposla+", "kaltakla+"], "f": ["kaltaklayman", "urib o'ldiraman"], "i": ["kaltaklang"]},
            "kk": {"b": ["ұрып-соғу", "соққыға жығу"], "f": ["ұрып тастаймын"], "i": ["ұрыңдар"]},
            "ky": {"b": ["сабоо", "уруп-согуу"], "f": ["сабайм"], "i": ["сабагыла"]},
            "tg": {"b": ["задукӯб"], "f": ["мезанамат"], "i": ["занедаш"]},
            "tr": {"b": ["dövüp öldür+"], "f": ["döveceğim"], "i": ["dövün"]},
        },
    },
    "death_to": {
        "label": "«смерть …» / пожелание смерти группе",
        "group": "violence",
        "severity": "severe",
        "terms": {
            "ru": {"i": ["смерть всем", "смерть им", "смерть неверным", "смерть кафирам", "смерть предателям", "смерть врагам", "сдохните все", "чтоб вы сдохли", "чтоб они сдохли"]},
            "en": {"i": ["death to", "all of you should die", "they all deserve to die", "they should all die"]},
            "fr": {"i": ["mort aux", "mort à tous", "qu'ils crèvent"]},
            "de": {"i": ["tod den", "tod allen", "sollen alle sterben"]},
            "es": {"i": ["muerte a", "que mueran todos", "mueran"]},
            "it": {"i": ["morte ai", "morte a", "che muoiano tutti"]},
            "ko": {"i": ["다 죽어라", "죽어 마땅"]},
            "ja": {"i": ["死ね", "くたばれ", "全員死ね"]},
            "zh": {"i": ["都去死", "死全家", "该死的都死"]},
            "fa": {"i": ["مرگ بر"]},
            "ar": {"i": ["الموت لل", "الموت لـ"]},
            "uz": {"i": ["o'lsin", "hammasi o'lsin", "yo'qolsin hammasi"]},
            "kk": {"i": ["өлсін", "өліңдер", "бәрі өлсін"]},
            "ky": {"i": ["өлсүн", "баары өлсүн"]},
            "tg": {"i": ["марг бар", "бимиранд"]},
            "tk": {"i": ["ölsün", "hemmesi ölsün"]},
            "tr": {"i": ["ölsün", "hepsi ölsün", "geberin"]},
        },
    },
    "destroy_group": {
        "label": "истребление / уничтожение группы",
        "group": "violence",
        "severity": "catastrophic",
        "terms": {
            "ru": {"b": ["истребить", "уничтожить всех", "вырезать всех", "перебить всех", "зачистить", "этническая чистка"], "f": ["уничтожим всех", "вырежем всех", "перебьём всех", "перебьем всех", "зачистим", "истребим"], "i": ["истребляйте", "уничтожайте их", "вырезайте"]},
            "en": {"b": ["exterminate", "wipe out", "eradicate them", "ethnic cleansing", "genocide them"], "f": ["we will wipe them out", "we will exterminate"], "i": ["wipe them out", "exterminate them"]},
            "fr": {"b": ["exterminer", "éradiquer", "anéantir"], "i": ["exterminez-les"]},
            "de": {"b": ["ausrotten", "vernichten", "auslöschen"], "i": ["rottet sie aus", "vernichtet sie"]},
            "es": {"b": ["exterminar", "aniquilar", "erradicar"], "i": ["extermínenlos"]},
            "it": {"b": ["sterminare", "annientare"], "i": ["sterminateli"]},
            "ko": {"b": ["몰살", "쓸어버리", "씨를 말리"]},
            "ja": {"b": ["皆殺し", "根絶やし", "抹殺"]},
            "zh": {"b": ["灭绝", "消灭", "斩尽杀绝"]},
            "fa": {"b": ["نابود کردن", "ریشه کن کردن"], "i": ["نابودشان کنید"]},
            "ar": {"b": ["إبادة", "استئصال"], "i": ["أبيدوهم"]},
            "uz": {"b": ["yo'q qilish", "qirib tashla+"], "f": ["qirib tashlaymiz", "yo'q qilamiz"], "i": ["qirib tashlang"]},
            "kk": {"b": ["қырып тастау", "құрту"], "f": ["қырып тастаймыз"], "i": ["қырып тастаңдар"]},
            "ky": {"b": ["кырып салуу", "жок кылуу"], "f": ["кырып салабыз"], "i": ["кырып салгыла"]},
            "tg": {"b": ["нобуд кардан", "қир кардан"], "f": ["нобуд мекунем"], "i": ["нобуд кунед"]},
            "tk": {"b": ["ýok etmek", "gyryp taşla+"], "i": ["gyryp taşlaň"]},
            "tr": {"b": ["yok et+", "soykırım", "kökünü kazı+"], "i": ["yok edin"]},
        },
    },
    "veiled_threat": {
        "label": "завуалированная угроза",
        "group": "violence",
        "severity": "significant",
        "terms": {
            "ru": {"f": ["тебе конец", "ему конец", "ей конец", "вам конец", "ты труп", "ты не жилец", "пожалеешь", "пожалеете", "мы тебя найдем", "мы тебя найдём", "я тебя найду", "знаю где ты живешь", "знаю где ты живёшь", "мы знаем где ты живешь", "жди гостей"]},
            "en": {"f": ["you're dead", "you are dead", "you'll regret", "you will regret", "watch your back", "we know where you live", "i know where you live", "you're next", "you are next", "i'll find you", "we will find you"]},
            "fr": {"f": ["tu es mort", "tu vas le regretter", "on sait où tu habites", "je sais où tu habites"]},
            "de": {"f": ["du bist tot", "du wirst es bereuen", "wir wissen wo du wohnst", "ich weiß wo du wohnst"]},
            "es": {"f": ["estás muerto", "te vas a arrepentir", "sabemos dónde vives", "sé dónde vives"]},
            "it": {"f": ["sei morto", "te ne pentirai", "sappiamo dove abiti", "so dove abiti"]},
            "ko": {"f": ["너 죽었어", "후회하게 될 거야", "어디 사는지 알아"]},
            "ja": {"f": ["覚えてろ", "後悔させてやる", "住所は知ってる"]},
            "zh": {"f": ["你死定了", "你会后悔的", "我知道你住哪"]},
            "fa": {"f": ["پشیمان میشوی", "میدانم کجا زندگی میکنی"]},
            "ar": {"f": ["ستندم", "نعرف أين تسكن", "أعرف أين تسكن"]},
            "uz": {"f": ["seni topamiz", "seni topaman", "qayerda yashashingni bilaman", "pushaymon bo'lasan"]},
            "kk": {"f": ["сені табамыз", "қайда тұратыныңды білемін", "өкінесің"]},
            "ky": {"f": ["сени табабыз", "кайда жашаарыңды билем", "өкүнөсүң"]},
            "tg": {"f": ["туро меёбем", "пушаймон мешавӣ"]},
            "tr": {"f": ["seni bulacağız", "nerede oturduğunu biliyorum", "pişman olacaksın", "sıra sende"]},
        },
    },
    "arrival": {
        "label": "заявленное намерение прийти/принести (значимо только вместе с оружием)",
        "group": "movement",
        "severity": "context",
        "terms": {
            "ru": {"f": ["приду", "приеду", "явлюсь", "заявлюсь", "нагряну", "принесу", "придём", "придем", "приедем"]},
            "en": {"f": ["i'll come", "i will come", "i'm coming", "im coming", "i'll bring", "i will bring", "i'm bringing", "we will come"]},
            "fr": {"f": ["je viendrai", "je vais venir", "j'apporterai"]},
            "de": {"f": ["ich komme", "ich werde kommen", "ich bringe"]},
            "es": {"f": ["voy a ir", "vendré", "traeré"]},
            "it": {"f": ["verrò", "porterò"]},
            "ko": {"f": ["갈 거야", "가져갈"]},
            "ja": {"f": ["行くから", "持って行く"]},
            "zh": {"f": ["我会去", "我要去", "带着"]},
            "fa": {"f": ["میام", "میآیم", "میارم"]},
            "ar": {"f": ["سآتي", "سأحضر"]},
            "uz": {"f": ["kelaman", "boraman", "olib kelaman"]},
            "kk": {"f": ["келемін", "барамын", "әкелемін"]},
            "ky": {"f": ["келем", "барам", "алып келем"]},
            "tg": {"f": ["меоям", "меравам", "меорам"]},
            "tk": {"f": ["gelerin", "bararyn"]},
            "tr": {"f": ["geleceğim", "gideceğim", "getireceğim"]},
        },
    },
    # ------------------------------------------------------------------ ОРУЖИЕ
    "weapon": {
        "label": "оружие",
        "group": "weapon",
        "severity": "context",
        "terms": {
            "ru": {"b": ["оружие", "оружия", "ружье", "ружьё", "ружьем", "ружьём", "пистолет*", "автомат калашникова", "калаш", "калашников*", "патрон", "патроны", "патронов", "нож", "ножом", "ножи", "тесак*", "граната", "гранату", "гранатомет*", "коктейль молотова", "коктейли молотова", "обрез", "карабин*"]},
            "en": {"b": ["gun", "guns", "rifle", "pistol", "handgun", "ammo", "ammunition", "knife", "machete", "grenade", "molotov", "ar-15", "ak-47", "shotgun"]},
            "fr": {"b": ["arme", "armes", "fusil", "pistolet", "munitions", "couteau", "grenade", "kalachnikov"]},
            "de": {"b": ["waffe", "waffen", "gewehr", "pistole", "munition", "messer", "granate"]},
            "es": {"b": ["arma", "armas", "rifle", "pistola", "munición", "cuchillo", "granada", "escopeta"]},
            "it": {"b": ["arma", "armi", "fucile", "pistola", "munizioni", "coltello", "granata"]},
            "ko": {"b": ["총기", "총을", "소총", "권총", "칼을", "흉기", "수류탄", "탄약"]},
            "ja": {"b": ["拳銃", "ライフル", "刃物", "ナイフ", "手榴弾", "弾薬", "銃を"]},
            "zh": {"b": ["枪支", "步枪", "手枪", "刀具", "匕首", "手榴弹", "子弹", "弹药"]},
            "fa": {"b": ["اسلحه", "تفنگ", "کلت", "چاقو", "نارنجک", "مهمات", "کلاشینکف"]},
            "ar": {"b": ["سلاح", "بندقية", "مسدس", "سكين", "قنبلة يدوية", "ذخيرة", "كلاشنكوف"]},
            "uz": {"b": ["qurol", "qurol-yarog'", "avtomat", "to'pponcha", "pichoq", "o'q-dori", "granata", "miltiq"]},
            "kk": {"b": ["қару", "мылтық", "тапанша", "пышақ", "оқ-дәрі", "граната"]},
            "ky": {"b": ["курал", "мылтык", "тапанча", "бычак", "ок-дары", "граната"]},
            "tg": {"b": ["силоҳ", "туфанг", "таппонча", "корд", "граната"]},
            "tk": {"b": ["ýarag", "tüpeň", "pisdolet", "pyçak", "ok-däri", "granata"]},
            "tr": {"b": ["silah", "tüfek", "tabanca", "bıçak", "mermi", "el bombası", "kalaşnikof"]},
        },
    },
    # --------------------------------------------------------------- ВЕРБОВКА
    "recruit_join": {
        "label": "призыв присоединиться",
        "group": "recruit",
        "severity": "severe",
        "terms": {
            "ru": {"i": ["присоединяйся к нам", "присоединяйтесь к нам", "присоединиться к муджахидам", "вступай в ряды", "вступайте в ряды", "иди к нам", "становись в строй", "ищем братьев", "нужны братья", "присягу", "присягните", "байа", "байат"]},
            "en": {"i": ["join us", "join the ranks", "join our brothers", "we need brothers", "pledge allegiance", "bay'ah", "enlist with"]},
            "fr": {"i": ["rejoignez-nous", "rejoins-nous", "rejoindre les rangs", "prêter allégeance"]},
            "de": {"i": ["schließ dich uns an", "schließt euch an", "tretet bei", "treueeid"]},
            "es": {"i": ["únete a nosotros", "únanse", "unirse a las filas", "jurar lealtad"]},
            "it": {"i": ["unisciti a noi", "unitevi", "giurare fedeltà"]},
            "ko": {"i": ["합류하라", "가입하라", "동참하라", "충성 맹세"]},
            "ja": {"i": ["参加せよ", "加われ", "忠誠を誓"]},
            "zh": {"i": ["加入我们", "加入圣战", "效忠"]},
            "fa": {"i": ["به ما بپیوندید", "بیعت"]},
            "ar": {"i": ["انضموا", "انضم إلينا", "بايعوا", "البيعة", "النفير", "انفروا"]},
            "uz": {"i": ["bizga qo'shiling", "safimizga qo'shil+", "saflarga qo'shil+", "bay'at"]},
            "kk": {"i": ["бізге қосылыңдар", "бізге қосылыңыз", "қатарымызға қосыл+"]},
            "ky": {"i": ["бизге кошулгула", "катарыбызга кошул+"]},
            "tg": {"i": ["ба мо ҳамроҳ шавед", "ба сафи мо", "байъат"]},
            "tk": {"i": ["bize goşulyň", "hatarymyza goşul+"]},
            "tr": {"i": ["bize katılın", "saflarımıza katıl+", "biat"]},
        },
    },
    "recruit_travel": {
        "label": "«хиджра» / логистика переезда",
        "group": "recruit",
        "severity": "severe",
        "terms": {
            "ru": {"b": ["хиджра", "хиджру", "хиджре", "переезжай на земли", "на земли халифата", "дорогу оплатим", "билеты оплатим", "поможем с дорогой", "переправим"]},
            "en": {"b": ["hijrah", "make hijra", "travel will be paid", "we cover the ticket", "we will help you travel"]},
            "fr": {"b": ["faire la hijra", "voyage payé"]},
            "de": {"b": ["hidschra", "reise bezahlt"]},
            "es": {"b": ["hégira", "viaje pagado"]},
            "it": {"b": ["egira", "viaggio pagato"]},
            "ar": {"b": ["الهجرة إلى أرض", "هاجروا إلى"]},
            "fa": {"b": ["هجرت به"]},
            "uz": {"b": ["hijrat", "yo'l haqini to'laymiz"]},
            "kk": {"b": ["хиджра", "жол ақысын төлейміз"]},
            "ky": {"b": ["хижрат", "жол киреңди төлөйбүз"]},
            "tg": {"b": ["ҳиҷрат", "хароҷоти роҳро медиҳем"]},
            "tk": {"b": ["hijrat"]},
            "tr": {"b": ["hicret", "yol masrafını karşılıyoruz"]},
        },
    },
    "ideology": {
        "label": "идеологический контекст (сам по себе не угроза)",
        "group": "ideology",
        "severity": "context",
        "terms": {
            "ru": {"b": ["джихад*", "муджахид*", "моджахед*", "шахид*", "халифат*", "кафир*", "тагут*", "игил", "даиш", "игил-хорасан", "вилаят хорасан", "аль-каида"]},
            "en": {"b": ["jihad*", "mujahid*", "shahid", "martyrdom", "caliphate", "khilafah", "kuffar", "kafir*", "taghut", "isis", "isil", "daesh", "iskp", "islamic state", "al-qaeda"]},
            "fr": {"b": ["djihad*", "jihad*", "moudjahid*", "califat", "mecreants", "kouffar"]},
            "de": {"b": ["dschihad*", "mudschahid*", "kalifat"]},
            "es": {"b": ["yihad*", "muyahidin", "califato"]},
            "it": {"b": ["jihad*", "mujaheddin", "califfato"]},
            "ko": {"b": ["지하드", "칼리프"]},
            "ja": {"b": ["ジハード", "聖戦", "カリフ制"]},
            "zh": {"b": ["圣战", "哈里发"]},
            "fa": {"b": ["جهاد", "مجاهد", "خلافت", "کافر"]},
            "ar": {"b": ["جهاد", "مجاهد", "استشهاد", "الخلافة", "الكفار", "الطاغوت", "الدولة الإسلامية", "داعش"]},
            "uz": {"b": ["jihod*", "mujohid*", "shahid*", "xalifalik", "kofir*", "tog'ut"]},
            "kk": {"b": ["жиһад*", "джихад*", "моджахед*", "халифат*", "кәпір*"]},
            "ky": {"b": ["жихад*", "моджахед*", "халифат*", "каапыр*"]},
            "tg": {"b": ["ҷиҳод*", "муҷоҳид*", "шаҳид*", "хилофат*", "кофир*"]},
            "tk": {"b": ["jihad*", "mujahid*", "halyfat*", "kapyr*"]},
            "tr": {"b": ["cihat*", "cihad*", "mücahit*", "mücahid*", "hilafet", "kafir*", "tağut", "deaş", "işid"]},
        },
    },
    "contact": {
        "label": "канал связи («пиши в лс», бот)",
        "group": "contact",
        "severity": "context",
        "terms": {
            "ru": {"b": ["пиши в лс", "пишите в лс", "в личку", "в личные сообщения", "пиши в бот", "пишите в бот", "пишите боту", "пиши боту", "ссылка в профиле", "ссылка в описании", "связь через бот", "пиши мне", "напиши мне"]},
            "en": {"b": ["dm me", "dm for", "message me", "contact via bot", "link in bio", "pm me", "telegram bot"]},
            "fr": {"b": ["écris-moi en privé", "en mp", "contacte le bot"]},
            "de": {"b": ["schreib mir privat", "per dm", "schreib dem bot"]},
            "es": {"b": ["escríbeme al privado", "por dm", "mándame un mensaje"]},
            "it": {"b": ["scrivimi in privato", "in dm"]},
            "ko": {"b": ["디엠", "개인 메시지", "텔레그램 봇"]},
            "ja": {"b": ["dmください", "個別に連絡"]},
            "zh": {"b": ["私信", "私聊", "加我"]},
            "fa": {"b": ["پیام خصوصی", "دایرکت"]},
            "ar": {"b": ["راسلني", "على الخاص", "تواصل عبر البوت"]},
            "uz": {"b": ["lichkaga yozing", "shaxsiyga yozing", "botga yozing", "menga yozing"]},
            "kk": {"b": ["жеке хабарға жазыңыз", "ботқа жазыңыз", "маған жаз"]},
            "ky": {"b": ["жеке билдирүүгө жазгыла", "ботко жазгыла", "мага жаз"]},
            "tg": {"b": ["ба шахсӣ нависед", "ба бот нависед"]},
            "tk": {"b": ["şahsy habara ýazyň"]},
            "tr": {"b": ["dm at", "özelden yaz", "bota yaz"]},
        },
    },
    # ------------------------------------------------------------------ ТРАВЛЯ
    "kys": {
        "label": "побуждение к самоповреждению",
        "group": "harass",
        "severity": "severe",
        "terms": {
            "ru": {"i": ["убей себя", "убейся", "иди повесься", "повесься", "вскройся", "выпились", "сдохни", "лучше бы ты сдох", "лучше бы ты сдохла"]},
            "en": {"i": ["kill yourself", "kys", "go die", "unalive yourself", "drink bleach", "hang yourself", "nobody would miss you"]},
            "fr": {"i": ["tue-toi", "va mourir", "crève"]},
            "de": {"i": ["bring dich um", "töte dich", "hang dich auf", "stirb"]},
            "es": {"i": ["mátate", "muérete", "ahórcate"]},
            "it": {"i": ["ammazzati", "ucciditi", "muori"]},
            "ko": {"i": ["자살해", "뒤져라", "죽어버려"]},
            "ja": {"i": ["自殺しろ", "消えろ"]},
            "zh": {"i": ["去死吧", "自杀吧"]},
            "fa": {"i": ["خودتو بکش", "بمیر"]},
            "ar": {"i": ["اقتل نفسك"]},
            "uz": {"i": ["o'zingni o'ldir", "o'zini o'ldirsin", "o'lib ket"]},
            "kk": {"i": ["өзіңді өлтір", "өліп кет", "асылып өл"]},
            "ky": {"i": ["өзүңдү өлтүр", "өлүп кал", "асылып өл"]},
            "tg": {"i": ["худатро куш", "бимир"]},
            "tk": {"i": ["özüňi öldür"]},
            "tr": {"i": ["kendini öldür", "geber", "git öl"]},
        },
    },
    "doxxing": {
        "label": "деанонимизация / раскрытие адреса",
        "group": "harass",
        "severity": "moderate",
        "terms": {
            "ru": {"i": ["re:найдите (?:его|ее|её|их) адрес", "re:найдите где (?:он|она|они) жив\\w*", "слейте адрес", "слить адрес", "слейте данные", "деанон*", "re:пробейте (?:его|ее|её|их)", "пробить по базе", "выложите адрес", "re:узнайте где (?:он|она) жив\\w*"]},
            "en": {"i": ["dox*", "doxx*", "re:find (?:his|her|their) address", "re:post (?:his|her|their) address", "re:leak (?:his|her|their) address", "re:find out where (?:he|she|they) li\\w+"]},
            "fr": {"i": ["trouvez son adresse", "balancez son adresse"]},
            "de": {"i": ["findet seine adresse", "findet ihre adresse", "adresse veröffentlichen"]},
            "es": {"i": ["encuentren su dirección", "publiquen su dirección"]},
            "it": {"i": ["trovate il suo indirizzo", "pubblicate il suo indirizzo"]},
            "ko": {"i": ["신상털기", "신상 털", "주소 알아내"]},
            "ja": {"i": ["特定しろ", "住所を晒せ", "晒せ"]},
            "zh": {"i": ["人肉搜索", "人肉他", "曝光他的地址"]},
            "fa": {"i": ["آدرسش را پیدا کنید"]},
            "ar": {"i": ["ابحثوا عن عنوانه", "انشروا عنوانه"]},
            "uz": {"i": ["manzilini toping", "manzilini tarqating", "qayerda yashashini toping"]},
            "kk": {"i": ["мекенжайын табыңдар", "қай жерде тұратынын табыңдар"]},
            "ky": {"i": ["дарегин тапкыла", "кайда жашаарын тапкыла"]},
            "tg": {"i": ["суроғаашро ёбед"]},
            "tr": {"i": ["adresini bulun", "adresini paylaşın", "ifşa edin"]},
        },
    },
    "mass_call": {
        "label": "призыв к массовой атаке на человека",
        "group": "harass",
        "severity": "moderate",
        "terms": {
            "ru": {"i": ["все пишем ему", "все пишем ей", "все пишем", "пишем все", "закидайте", "закидаем", "кидайте репорты", "массово жалуйтесь", "устроим травлю", "затравить", "затравим", "атакуем аккаунт", "рейд на"]},
            "en": {"i": ["everyone report", "mass report", "raid his", "raid her", "spam him", "spam her", "flood his dms", "flood her dms", "brigade"]},
            "fr": {"i": ["tout le monde le signale", "harcelez-le", "harcelez-la"]},
            "de": {"i": ["alle melden", "shitstorm"]},
            "es": {"i": ["todos a reportar", "funémosle"]},
            "it": {"i": ["segnalatelo tutti"]},
            "ko": {"i": ["다 같이 신고", "좌표 찍"]},
            "ja": {"i": ["凸しよう", "晒し上げ", "みんなで通報"]},
            "zh": {"i": ["网暴", "一起举报", "冲他"]},
            "fa": {"i": ["همه گزارش کنید"]},
            "ar": {"i": ["الجميع يبلغ عنه"]},
            "uz": {"i": ["hammamiz unga yozamiz", "hammamiz yozamiz", "hammamiz shikoyat qilamiz"]},
            "kk": {"i": ["бәріміз жазамыз", "бәріміз шағымданамыз"]},
            "ky": {"i": ["баарыбыз жазабыз"]},
            "tg": {"i": ["ҳама менависем"]},
            "tr": {"i": ["herkes şikayet etsin", "hep birlikte yazalım", "linç"]},
        },
    },
    "insult": {
        "label": "адресное оскорбление",
        "group": "harass",
        "severity": "moderate",
        "terms": {
            "ru": {"b": ["мразь", "тварь", "ублюдок", "ничтожество", "конченый", "конченая", "падаль", "выродок"]},
            "en": {"b": ["piece of shit", "scum", "worthless", "loser"]},
            "uz": {"b": ["haromi", "iflos", "ahmoq"]},
            "kk": {"b": ["оңбаған"]},
            "ky": {"b": ["акмак", "шерменде"]},
            "tg": {"b": ["аблаҳ", "нокас"]},
        },
    },
    # --------------------------------------------------- ПОДСТРЕКАТЕЛЬСТВО К РОЗНИ
    "dehumanize": {
        "label": "расчеловечивание",
        "group": "dehumanize",
        "severity": "moderate",
        "terms": {
            "ru": {"b": ["тараканы", "тараканов", "крысы", "паразиты", "паразитов", "нелюди", "нелюдь", "не люди", "скоты", "зверье", "зверьё", "вши", "нечисть", "саранча", "раковая опухоль", "животные"]},
            "en": {"b": ["cockroaches", "vermin", "rats", "parasites", "subhuman*", "not human", "infestation", "animals"]},
            "fr": {"b": ["cafards", "vermine", "parasites", "sous-hommes", "pas des humains"]},
            "de": {"b": ["kakerlaken", "ungeziefer", "ratten", "parasiten", "untermenschen", "keine menschen"]},
            "es": {"b": ["cucarachas", "alimañas", "ratas", "parásitos", "infrahumanos", "no son humanos"]},
            "it": {"b": ["scarafaggi", "parassiti", "ratti", "subumani", "non sono umani"]},
            "ko": {"b": ["바퀴벌레", "벌레들", "기생충", "쥐새끼"]},
            "ja": {"b": ["ゴキブリ", "害虫", "寄生虫", "ウジ虫", "人間じゃない"]},
            "zh": {"b": ["蟑螂", "害虫", "寄生虫", "畜生", "不是人"]},
            "fa": {"b": ["سوسک", "انگل"]},
            "ar": {"b": ["صراصير", "حشرات", "جرذان", "طفيليات", "ليسوا بشرا"]},
            "uz": {"b": ["tarakanlar", "kalamushlar", "parazitlar", "odam emas"]},
            "kk": {"b": ["тарақандар", "егеуқұйрықтар", "паразиттер", "адам емес"]},
            "ky": {"b": ["таракандар", "келемиштер", "адам эмес"]},
            "tg": {"b": ["тараканҳо", "калламушҳо", "одам нестанд"]},
            "tk": {"b": ["tarakanlar", "adam däl"]},
            "tr": {"b": ["hamamböcekleri", "fareler", "parazitler", "insan değil"]},
        },
    },
    "expel": {
        "label": "призыв к изгнанию",
        "group": "expel",
        "severity": "moderate",
        "terms": {
            "ru": {"i": ["выгнать", "выгоним", "выгоняйте", "изгнать", "вышвырнуть", "депортировать всех", "очистить город от", "очистить страну от", "чтоб духу не было", "гнать их"]},
            "en": {"i": ["kick them out", "expel them", "drive them out", "send them all back", "deport them all"]},
            "fr": {"i": ["chassez-les", "expulsez-les", "virez-les tous"]},
            "de": {"i": ["rausschmeißen", "schiebt sie ab", "vertreibt sie"]},
            "es": {"i": ["échenlos", "expúlsenlos", "deportar a todos"]},
            "it": {"i": ["cacciateli", "espelleteli", "rimandateli a casa"]},
            "ko": {"i": ["쫓아내", "추방하라", "내쫓아"]},
            "ja": {"i": ["追い出せ", "叩き出せ"]},
            "zh": {"i": ["赶出去", "滚出", "驱逐他们"]},
            "fa": {"i": ["بیرونشان کنید", "اخراجشان کنید"]},
            "ar": {"i": ["اطردوهم", "اطردوا"]},
            "uz": {"i": ["haydab chiqar+", "haydang", "quvib chiqar+"]},
            "kk": {"i": ["қуып шығу", "қуып шығамыз", "қуыңдар"]},
            "ky": {"i": ["кууп чыгуу", "кууп чыгабыз", "кугула"]},
            "tg": {"i": ["ронда баровардан", "ронед"]},
            "tk": {"i": ["kowup çykar+"]},
            "tr": {"i": ["sınır dışı edin", "defedin", "kovun"]},
        },
    },
    # ------------------------------------------------------ ОПАСНОЕ ВОВЛЕЧЕНИЕ
    "paid_task": {
        "label": "оплачиваемое «задание»",
        "group": "involve",
        "severity": "significant",
        "terms": {
            "ru": {"b": ["легкий заработок", "лёгкий заработок", "быстрый заработок", "быстрые деньги", "оплата сразу", "оплата в крипте", "оплата в usdt", "платим сразу", "хорошо заплатим", "нужны ребята", "работа на один день", "задание за деньги"]},
            "en": {"b": ["easy money", "quick money", "quick cash", "paid immediately", "pay in crypto", "paid in usdt", "one-time job", "we pay well"]},
            "fr": {"b": ["argent facile", "payé tout de suite"]},
            "de": {"b": ["schnelles geld", "sofortige bezahlung"]},
            "es": {"b": ["dinero fácil", "pago inmediato"]},
            "it": {"b": ["soldi facili", "pagamento immediato"]},
            "ko": {"b": ["고수익 알바", "쉬운 돈"]},
            "ja": {"b": ["闇バイト", "高額バイト", "即日払い"]},
            "zh": {"b": ["轻松赚钱", "高薪兼职", "当天结算"]},
            "fa": {"b": ["پول آسان", "پرداخت فوری"]},
            "ar": {"b": ["ربح سهل", "مال سريع", "دفع فوري"]},
            "uz": {"b": ["oson pul", "tez pul", "darhol to'lov", "kriptoda to'lov", "yigitlar kerak"]},
            "kk": {"b": ["оңай ақша", "тез ақша", "бірден төлейміз", "жігіттер керек"]},
            "ky": {"b": ["оңой акча", "тез акча", "дароо төлөйбүз", "жигиттер керек"]},
            "tg": {"b": ["пули осон", "пули зуд", "фавран пардохт", "бачаҳо лозим"]},
            "tk": {"b": ["aňsat pul", "çalt pul"]},
            "tr": {"b": ["kolay para", "hızlı para", "hemen ödeme", "kripto ile ödeme"]},
        },
    },
    "sabotage": {
        "label": "диверсия / поджог объектов",
        "group": "involve",
        "severity": "significant",
        "terms": {
            "ru": {"b": ["релейный шкаф", "релейные шкафы", "релейного шкафа", "вышку связи", "вышка связи", "диверсия", "диверсии", "поджечь машину", "поджечь автомобиль", "поджечь военкомат", "заснять военн*", "сфотографировать военн*"]},
            "en": {"b": ["sabotage", "relay cabinet", "cell tower", "set fire to a car", "photograph military", "film military convoy"]},
            "fr": {"b": ["sabotage"]}, "de": {"b": ["sabotage"]}, "es": {"b": ["sabotaje"]}, "it": {"b": ["sabotaggio"]},
            "ko": {"b": ["사보타주", "방해 공작"]}, "ja": {"b": ["破壊工作"]}, "zh": {"b": ["破坏活动"]},
            "fa": {"b": ["خرابکاری"]}, "ar": {"b": ["تخريب"]},
            "uz": {"b": ["diversiya"]}, "kk": {"b": ["диверсия"]}, "ky": {"b": ["диверсия"]}, "tg": {"b": ["диверсия"]},
            "tk": {"b": ["diwersiýa"]}, "tr": {"b": ["sabotaj"]},
        },
    },
    "minors": {
        "label": "упоминание несовершеннолетних",
        "group": "involve",
        "severity": "context",
        "terms": {
            "ru": {"b": ["школьник*", "подросток", "подростки", "подростков", "несовершеннолетн*", "малолетк*", "re:\\b1[2-7] ?\\+"]},
            "en": {"b": ["teens", "teenagers", "minors", "schoolkids", "under 18", "re:\\b1[2-7] ?\\+"]},
            "fr": {"b": ["ados", "adolescents", "mineurs", "collegiens", "lyceens"]},
            "de": {"b": ["jugendliche", "minderjahrige", "schuler"]},
            "es": {"b": ["adolescentes", "menores de edad"]},
            "it": {"b": ["adolescenti", "minorenni"]},
            "ko": {"b": ["청소년", "미성년자"]},
            "ja": {"b": ["未成年", "中高生"]},
            "zh": {"b": ["未成年", "青少年"]},
            "fa": {"b": ["نوجوانان", "زیر ۱۸"]},
            "ar": {"b": ["المراهقين", "القاصرين"]},
            "uz": {"b": ["o'smirlar", "maktab o'quvchilari", "voyaga yetmagan*"]},
            "kk": {"b": ["жасөспірім*", "оқушылар", "кәмелетке толмаған*"]},
            "ky": {"b": ["өспүрүм*", "окуучулар", "жашы жете элек"]},
            "tg": {"b": ["наврасон", "мактаббачагон", "ноболиғ*"]},
            "tk": {"b": ["ýetginjekler", "okuwçylar"]},
            "tr": {"b": ["liseliler", "reşit olmayan*"]},
        },
    },
    "challenge": {
        "label": "опасные «игры» / «кураторы»",
        "group": "involve",
        "severity": "significant",
        "terms": {
            "ru": {"b": ["синий кит", "тихий дом", "разбуди меня в 4:20", "f57", "игра смерти", "группы смерти", "куратор даст задание"]},
            "en": {"b": ["blue whale challenge", "deadly challenge", "death group", "the curator will give"]},
            "fr": {"b": ["baleine bleue", "défi mortel"]},
            "de": {"b": ["blue-whale-challenge"]},
            "es": {"b": ["ballena azul", "reto mortal"]},
            "it": {"b": ["balena blu"]},
            "ko": {"b": ["대왕고래"]}, "ja": {"b": ["青い鯨"]}, "zh": {"b": ["蓝鲸游戏"]},
            "fa": {"b": ["نهنگ آبی"]}, "ar": {"b": ["الحوت الأزرق"]},
            "uz": {"b": ["ko'k kit", "o'lim guruhlari"]}, "kk": {"b": ["көк кит", "өлім топтары"]},
            "ky": {"b": ["көк кит"]}, "tg": {"b": ["гурӯҳҳои марг"]}, "tr": {"b": ["mavi balina"]},
        },
    },
    "school_attack_glorification": {
        "label": "героизация нападений на школы",
        "group": "warning",
        "severity": "severe",
        "terms": {
            "ru": {"b": ["колумбайн*", "скулшутинг*", "скулшут*", "повторить колумбайн"]},
            "en": {"b": ["columbine", "school shooter", "do a columbine"]},
            "uz": {"b": ["kolumbayn"]}, "kk": {"b": ["колумбайн"]}, "ky": {"b": ["колумбайн"]},
            "zh": {"b": ["哥伦拜恩"]}, "ja": {"b": ["コロンバイン"]}, "ko": {"b": ["콜럼바인"]},
        },
    },
    # ------------------------------------------------- ТРЕВОЖНЫЕ ПРИЗНАКИ (TRAP-18)
    "leakage": {
        "label": "«утечка» намерения третьим лицам",
        "group": "warning",
        "severity": "context",
        "terms": {
            "ru": {"b": ["скоро все узнают", "пусть все узнают", "все узнают", "вы обо мне услышите", "завтра узнаете", "запомните этот день", "это мой последний пост", "мой последний пост", "последнее сообщение"]},
            "en": {"b": ["you'll all see", "you will all see", "remember my name", "remember this day", "this is my last post", "my last post", "you'll hear about me"]},
            "fr": {"b": ["vous allez tous voir", "mon dernier post"]},
            "de": {"b": ["ihr werdet alle sehen", "mein letzter post"]},
            "es": {"b": ["todos lo verán", "mi último post"]},
            "it": {"b": ["lo vedrete tutti", "il mio ultimo post"]},
            "ko": {"b": ["다들 보게 될 거", "마지막 글"]},
            "ja": {"b": ["最後の投稿", "みんな思い知る"]},
            "zh": {"b": ["最后一条", "你们会看到的"]},
            "fa": {"b": ["همه خواهید دید", "آخرین پست"]},
            "ar": {"b": ["سترون جميعا", "آخر منشور"]},
            "uz": {"b": ["hammangiz bilasiz", "oxirgi postim", "bu kunni eslab qoling"]},
            "kk": {"b": ["бәрің білесіңдер", "соңғы постым", "көресіңдер"]},
            "ky": {"b": ["баарыңар билесиңер", "акыркы постум", "көрөсүңөр"]},
            "tg": {"b": ["ҳама мефаҳманд", "охирин паём"]},
            "tr": {"b": ["hepiniz göreceksiniz", "son paylaşımım"]},
        },
    },
    "last_resort": {
        "label": "«последний довод»",
        "group": "warning",
        "severity": "context",
        "terms": {
            "ru": {"b": ["у меня нет выбора", "другого выхода нет", "нет другого выхода", "терять нечего", "мне нечего терять", "прощайте все"]},
            "en": {"b": ["no other choice", "no other way", "nothing to lose", "goodbye everyone", "goodbye world"]},
            "fr": {"b": ["pas d'autre choix", "rien à perdre", "adieu à tous"]},
            "de": {"b": ["keine andere wahl", "nichts zu verlieren", "lebt wohl"]},
            "es": {"b": ["no tengo otra opción", "nada que perder", "adiós a todos"]},
            "it": {"b": ["non ho altra scelta", "niente da perdere", "addio a tutti"]},
            "ko": {"b": ["다른 선택이 없다", "잃을 게 없다"]},
            "ja": {"b": ["他に道はない", "失うものは何もない"]},
            "zh": {"b": ["别无选择", "没什么可失去"]},
            "fa": {"b": ["چاره دیگری ندارم", "چیزی برای از دست دادن ندارم"]},
            "ar": {"b": ["لا خيار آخر", "لا شيء لأخسره"]},
            "uz": {"b": ["boshqa yo'l yo'q", "yo'qotadigan narsam yo'q", "alvido hammaga"]},
            "kk": {"b": ["басқа жол жоқ", "жоғалтар ештеңем жоқ", "қош болыңдар"]},
            "ky": {"b": ["башка жол жок", "жоготор эч нерсем жок", "кош болгула"]},
            "tg": {"b": ["роҳи дигар нест", "алвидо ҳама"]},
            "tr": {"b": ["başka çarem yok", "kaybedecek bir şeyim yok", "elveda herkese"]},
        },
    },
}

# Для основ («слово*») в агглютинативных языках форма определяется по окончанию.
# Порядок важен: проверяются по очереди, пустая строка — голая основа.
SUFFIX_FORMS: dict[str, list[tuple[str, str]]] = {
    "uz": [("aman", "f"), ("amiz", "f"), ("ayman", "f"), ("aymiz", "f"), ("ingiz", "i"), ("inglar", "i"), ("ing", "i"), ("sin", "i"), ("", "i")],
    "kk": [("емін", "f"), ("амын", "f"), ("еміз", "f"), ("амыз", "f"), ("ймын", "f"), ("ймін", "f"), ("іңдер", "i"), ("ыңдар", "i"), ("іңіз", "i"), ("ыңыз", "i"), ("сін", "i"), ("сын", "i"), ("", "i")],
    "ky": [("өм", "f"), ("ом", "f"), ("эм", "f"), ("ем", "f"), ("ам", "f"), ("өбүз", "f"), ("обуз", "f"), ("ебиз", "f"), ("абыз", "f"), ("гүлө", "i"), ("гула", "i"), ("гыла", "i"), ("гиле", "i"), ("ңүз", "i"), ("ңыз", "i"), ("сүн", "i"), ("сун", "i"), ("", "i")],
    "tr": [("ecegim", "f"), ("acagim", "f"), ("ecegiz", "f"), ("acagiz", "f"), ("in", "i"), ("un", "i"), ("sin", "i"), ("sun", "i"), ("", "i")],
    "tk": [("erin", "f"), ("aryn", "f"), ("eris", "f"), ("arys", "f"), ("jek", "f"), ("jak", "f"), ("inler", "i"), ("ynlar", "i"), ("in", "i"), ("yn", "i"), ("", "i")],
    "tg": [("ам", "f"), ("ем", "f"), ("ед", "i")],
}

# Отрицание внутри слова (основа + отрицательный аффикс)
NEGATION_SUFFIXES: dict[str, tuple[str, ...]] = {
    "uz": ("ma", "may"),
    "tr": ("me", "ma"),
    "tk": ("me", "ma"),
    "kk": ("ме", "ма", "бе", "ба", "пе", "па"),
    "ky": ("ба", "бе", "бо", "бө", "па", "пе", "по", "пө", "ма", "ме", "мо", "мө"),
}
# Аффиксы, которые начинаются как отрицание, но им не являются (инфинитив)
NEGATION_EXCLUDE: dict[str, tuple[str, ...]] = {
    "tr": ("mek", "mak"),
    "tk": ("mek", "mak"),
    "kk": ("мек", "мақ"),
    "ky": ("мак", "мек", "мок", "мөк"),
    "uz": ("moq",),
}
