"""Маркеры контекста (рамки) и конкретности угрозы по языкам.

Синтаксис терминов тот же, что в ``lexicon_data``: ``*`` — основа,
``re:`` — регулярное выражение по нормализованному тексту (нижний регистр,
без диакритики латиницы, «ё» → «е», арабская графика унифицирована).
"""

MARKERS: dict[str, dict[str, list[str]]] = {
    # ------------------------------------------------------------ РАМКА (framing)
    "quote_verbs": {
        "ru": ["сказал", "сказала", "заявил", "заявила", "написал", "написала", "пишет", "цитирую", "цитата", "по словам", "утверждает", "говорит", "процитировал*"],
        "en": ["said", "says", "wrote", "quoted", "according to", "claims", "stated", "quote", "the villain says", "the character says"],
        "fr": ["a dit", "a declare", "selon", "ecrit", "cite"],
        "de": ["sagte", "schrieb", "erklarte", "laut", "zitiert"],
        "es": ["dijo", "escribio", "segun", "declaro", "cita"],
        "it": ["ha detto", "ha scritto", "secondo", "dichiarato", "la frase", "riporta"],
        "ko": ["말했다", "밝혔다", "썼다", "인용"],
        "ja": ["と述べた", "と書いた", "によると", "引用"],
        "zh": ["写道", "据称", "引述", "声称"],
        "fa": ["گفت", "نوشت", "به گفته", "نقل قول"],
        "ar": ["قال", "كتب", "وفقا", "صرح", "نقلا عن"],
        "uz": ["dedi", "deb yozdi", "iqtibos", "so'zlariga ko'ra"],
        "kk": ["деді", "деп жазды", "сөзіне қарағанда"],
        "ky": ["деди", "деп жазды", "сөзүнө караганда"],
        "tg": ["гуфт", "навишт", "ба гуфтаи"],
        "tk": ["diýdi", "ýazdy"],
        "tr": ["dedi", "yazdı", "alıntı"],
    },
    "journalism": {
        "ru": ["сообщает", "сообщил", "сообщила", "сообщили", "по данным", "задержан*", "возбуждено уголовное дело", "уголовное дело", "мвд", "гкнб", "сгб", "дкнб", "увд", "полиция", "полиции", "прокуратур*", "суд", "приговор*", "следстви*", "корреспондент*", "пресс-служб*", "информагентство", "угрожал*", "грозил*", "пострадавш*", "погибли", "погибших"],
        "en": ["police", "arrested", "detained", "charged", "court", "sentenced", "prosecutors", "authorities", "reported", "officials", "investigation", "spokesperson", "threatened to", "victims", "were killed", "news"],
        "fr": ["police", "arrete", "interpelle", "mis en examen", "tribunal", "condamne", "a annonce", "enquete", "parquet", "victimes"],
        "de": ["polizei", "festgenommen", "verhaftet", "gericht", "verurteilt", "staatsanwaltschaft", "ermittlungen", "berichtet", "mitteilte", "gedroht", "opfer"],
        "es": ["policia", "detenido", "arrestado", "tribunal", "condenado", "fiscalia", "investigacion", "informo", "amenazo", "victimas"],
        "it": ["polizia", "arrestato", "fermato", "tribunale", "condannato", "procura", "indagine", "ha reso noto", "carabinieri", "aggressore", "giornale", "vittime"],
        "ko": ["경찰", "체포", "검거", "법원", "검찰", "수사", "기소", "보도", "예고한"],
        "ja": ["警察", "逮捕", "裁判所", "検察", "捜査", "起訴", "発表", "報道"],
        "zh": ["警方", "逮捕", "拘留", "法院", "检察", "调查", "据报道", "通报"],
        "fa": ["پلیس", "بازداشت", "دستگیر", "دادگاه", "دادستانی", "تحقیقات", "گزارش"],
        "ar": ["الشرطة", "اعتقال", "القبض", "المحكمة", "النيابة", "التحقيق", "أعلنت", "أفادت", "هدد"],
        "uz": ["xabar berdi", "ma'lum qildi", "hibsga olindi", "ushlandi", "jinoyat ishi", "iiv", "dxx", "prokuratura", "sud", "militsiya", "politsiya"],
        "kk": ["хабарлады", "мәлімдеді", "ұсталды", "қамауға алынды", "қылмыстық іс", "ііМ", "ұқк", "полиция", "сот", "прокуратура"],
        "ky": ["билдирди", "кабарлады", "кармалды", "камакка алынды", "кылмыш иши", "иим", "укмк", "милиция", "сот", "прокуратура", "шектелген", "шектүү"],
        "tg": ["хабар дод", "иттилоъ дод", "боздошт шуд", "парвандаи ҷиноӣ", "вкд", "кдам", "милитсия", "суд", "прокуратура"],
        "tk": ["habar berdi", "tussag edildi", "jenaýat işi", "polisiýa", "kazyýet", "prokuratura"],
        "tr": ["gözaltına alındı", "tutuklandı", "polis", "mahkeme", "savcılık", "bildirdi", "açıkladı"],
    },
    "condemnation": {
        "ru": ["осуждаю", "осуждаем", "осуждает", "недопустим*", "нет терроризму", "нет насилию", "против насилия", "скорбим", "соболезну*", "соболезнования", "это преступление", "терроризм не имеет"],
        "en": ["condemn*", "no to violence", "against violence", "we mourn", "condolences", "terrorism has no religion", "never acceptable", "stop the violence", "never a solution"],
        "fr": ["condamne", "condamnons", "non a la violence", "condoleances", "inacceptable", "jamais une solution"],
        "de": ["verurteile", "verurteilen", "keine gewalt", "beileid", "inakzeptabel", "nie eine losung"],
        "es": ["condeno", "condenamos", "no a la violencia", "condolencias", "inaceptable", "nunca es la solucion"],
        "it": ["condanno", "condanniamo", "no alla violenza", "condoglianze", "inaccettabile", "mai una soluzione"],
        "ko": ["규탄", "애도", "폭력 반대", "용납할 수 없"],
        "ja": ["非難する", "哀悼", "暴力反対", "許されない"],
        "zh": ["谴责", "哀悼", "反对暴力", "不可接受"],
        "fa": ["محکوم میکنیم", "محکوم", "تسلیت", "نه به خشونت"],
        "ar": ["ندين", "نستنكر", "تعازينا", "لا للعنف", "الإرهاب لا دين له"],
        "uz": ["qoralaymiz", "qoralayman", "zo'ravonlikka yo'q", "zo'ravonlikni qoralaymiz", "hamdardlik", "ta'ziya", "terrorizmning dini yo'q"],
        "kk": ["айыптаймыз", "айыптаймын", "көңіл айтамыз", "қайғырамыз", "терроризмнің діні жоқ"],
        "ky": ["айыптайбыз", "көңүл айтабыз", "кайгырабыз", "зордук-зомбулукка жол жок"],
        "tg": ["маҳкум мекунем", "ҳамдардӣ", "тасаллият", "терроризм дин надорад"],
        "tk": ["ýazgarýarys", "gynanýarys", "hamdardlyk"],
        "tr": ["kınıyoruz", "lanetliyoruz", "başsağlığı", "terörün dini yoktur"],
    },
    "fiction": {
        "ru": ["в игре", "катк*", "раунд*", "в фильме", "фильм*", "сериал*", "трейлер*", "книг*", "персонаж*", "злодей", "песня", "текст песни", "кс", "дота", "доте", "пабг", "майнкрафт", "гта", "роблокс"],
        "en": ["game", "next round", "gg", "ez", "movie", "film", "trailer", "series", "episode", "book", "novel", "character", "villain", "lyrics", "song", "minecraft", "fortnite", "valorant", "cs2", "csgo", "dota", "pubg", "roblox"],
        "fr": ["jeu", "partie", "film", "serie", "bande-annonce", "livre", "personnage"],
        "de": ["spiel", "runde", "film", "serie", "trailer", "buch", "figur"],
        "es": ["juego", "partida", "pelicula", "serie", "trailer", "libro", "personaje"],
        "it": ["gioco", "partita", "film", "serie", "trailer", "libro", "personaggio"],
        "ko": ["게임", "영화", "드라마"],
        "ja": ["ゲーム", "映画", "ドラマ"],
        "zh": ["游戏", "电影", "电视剧"],
        "fa": ["بازی", "فیلم", "سریال"],
        "ar": ["لعبة", "فيلم", "مسلسل"],
        "uz": ["o'yin", "kino", "serial"],
        "kk": ["ойын", "фильм", "кино"],
        "ky": ["оюн", "тасма", "кино"],
        "tg": ["бозӣ", "филм"],
        "tr": ["oyun", "film", "dizi"],
    },
    "humor": {
        "ru": ["ахах*", "хаха*", "лол", "шучу", "шутка", "шутки ради", "ржу"],
        "en": ["lol", "lmao", "jk", "just kidding", "joking", "haha*"],
        "fr": ["mdr", "ptdr", "je rigole", "blague"],
        "de": ["haha*", "witz", "spass"],
        "es": ["jaja*", "broma", "es broma"],
        "it": ["ahah*", "scherzo", "scherzavo"],
        "ko": ["ㅋㅋ", "농담"],
        "ja": ["冗談", "ｗｗ", "(笑)"],
        "zh": ["哈哈", "开玩笑"],
        "fa": ["شوخی"],
        "ar": ["هههه", "مزاح"],
        "uz": ["hazil", "hazillashdim"],
        "kk": ["әзіл", "қалжың"],
        "ky": ["тамаша", "азил"],
        "tg": ["шӯхӣ"],
        "tr": ["şaka", "sjsj"],
    },
    "protest": {
        "ru": ["митинг*", "протест*", "мирн*", "отставк*", "коррупци*", "выборы", "выборов", "требуем", "забастовк*", "петици*", "правительств*", "хоким*", "аким*", "оппозици*", "права человека", "без насилия", "свободу слова"],
        "en": ["protest*", "rally", "peaceful", "resign*", "corruption", "election*", "petition", "strike", "government", "opposition", "human rights", "free speech", "nonviolent"],
        "fr": ["manifestation", "greve", "demission", "corruption", "election*", "petition", "gouvernement", "pacifique"],
        "de": ["demonstration", "protest*", "rucktritt", "korruption", "wahl*", "petition", "regierung", "friedlich", "streik"],
        "es": ["protesta*", "manifestacion", "dimision", "renuncia", "corrupcion", "elecciones", "gobierno", "pacifica", "huelga"],
        "it": ["protesta*", "manifestazione", "dimissioni", "corruzione", "elezioni", "governo", "pacifica", "sciopero"],
        "ko": ["시위", "집회", "사퇴", "부패", "선거", "정부", "평화"],
        "ja": ["デモ", "抗議", "辞任", "汚職", "選挙", "政府", "平和的"],
        "zh": ["抗议", "示威", "辞职", "腐败", "选举", "政府", "和平"],
        "fa": ["اعتراض", "تظاهرات", "استعفا", "فساد", "انتخابات", "دولت", "مسالمت"],
        "ar": ["احتجاج", "مظاهرة", "استقالة", "فساد", "انتخابات", "الحكومة", "سلمي"],
        "uz": ["miting", "norozilik", "namoyish", "iste'fo", "korrupsiya", "poraxo'rlik", "saylov", "talab qilamiz", "hukumat", "hokim*", "tinch"],
        "kk": ["митинг", "наразылық", "шеру", "отставка", "сыбайлас жемқорлық", "сайлау", "талап етеміз", "үкімет", "әкім*", "бейбіт"],
        "ky": ["митинг", "нааразылык", "отставка", "коррупция", "шайлоо", "талап кылабыз", "өкмөт", "аким*", "тынч"],
        "tg": ["митинг", "эътироз", "истеъфо", "фасод", "интихобот", "ҳукумат", "осоишта"],
        "tk": ["miting", "nägilelik", "saýlaw", "hökümet", "parahor"],
        "tr": ["protesto", "miting", "istifa", "yolsuzluk", "seçim", "hükümet", "barışçıl", "grev"],
    },
    "religious": {
        "ru": ["намаз*", "молитв*", "рамадан*", "ураза", "ораза", "курбан", "ифтар*", "пасх*", "рождеств*", "коран*", "библи*", "хадж"],
        "en": ["prayer", "ramadan", "easter", "christmas", "quran", "bible", "eid", "hajj", "god bless"],
        "fr": ["priere", "ramadan", "paques", "noel", "coran", "bible", "aid"],
        "de": ["gebet", "ramadan", "ostern", "weihnachten", "koran", "bibel"],
        "es": ["oracion", "ramadan", "pascua", "navidad", "coran", "biblia"],
        "it": ["preghiera", "ramadan", "pasqua", "natale", "corano", "bibbia"],
        "ko": ["기도", "라마단", "성경", "부활절", "크리스마스"],
        "ja": ["祈り", "ラマダン", "聖書", "クリスマス"],
        "zh": ["祈祷", "斋月", "圣经", "圣诞", "古兰经"],
        "fa": ["نماز", "دعا", "رمضان", "روزه", "عید", "قرآن"],
        "ar": ["رمضان", "صلاة", "الصيام", "عيد", "القرآن", "الحج", "تقبل الله", "رمضان كريم"],
        "uz": ["namoz", "duo", "ramazon", "ro'za", "iftor", "qur'on", "hayit", "haj"],
        "kk": ["намаз", "дұға", "рамазан", "ораза", "ауызашар", "құран", "айт", "қажылық"],
        "ky": ["намаз", "дуба", "рамазан", "орозо", "ифтар", "куран", "айт", "ажылык"],
        "tg": ["намоз", "дуо", "рамазон", "рӯза", "ифтор", "қуръон", "ид", "ҳаҷ"],
        "tk": ["namaz", "doga", "oraza", "gurban", "baýram", "ramazan", "kuran"],
        "tr": ["namaz", "dua", "ramazan", "oruç", "bayram", "kuran", "hac"],
    },
    # ------------------------------------------------------- НАМЕРЕНИЕ / ПРИЗЫВ
    "intent": {
        "ru": ["re:\\b(?:я|мы)\\s+(?:буду|будем|собираюсь|собираемся|хочу|хотим|пойду|пойдем|иду|идем|планирую|планируем|готов|готовы)\\b"],
        "en": ["re:\\b(?:i|we)\\s*(?:'ll|will|am going to|'m going to|m going to|are going to|'re going to|re going to|gonna|plan to|want to|wanna|intend to|shall)\\b", "re:\\bim going to\\b"],
        "fr": ["re:\\b(?:je|j'|nous|on)\\s*(?:vais|allons|va|veux|voulons|compte|comptons)\\b"],
        "de": ["re:\\b(?:ich|wir)\\s+(?:werde|werden|will|wollen|plane|planen)\\b"],
        "es": ["re:\\b(?:voy|vamos)\\s+a\\b", "re:\\b(?:quiero|queremos)\\b"],
        "it": ["re:\\b(?:voglio|vogliamo|sto per|stiamo per|vado a|andiamo a)\\b"],
        "zh": ["我要", "我会", "我们要", "我准备", "我打算"],
        "ja": ["てやる", "つもり", "する予定"],
        "ko": ["거야", "겠다", "버릴"],
        "fa": ["خواهم", "میخواهم"],
        "ar": ["سوف"],
    },
    "obligation": {
        "ru": ["нужно", "надо", "необходимо", "должны", "пора", "следует", "давайте"],
        "en": ["must", "should", "need to", "have to", "it's time to", "let's"],
        "fr": ["il faut", "doit", "doivent", "allons"],
        "de": ["muss", "mussen", "sollte", "sollten", "lasst uns"],
        "es": ["hay que", "deben", "debemos", "tenemos que", "vamos a"],
        "it": ["bisogna", "dobbiamo", "devono", "bisognerebbe"],
        "ko": ["해야 한다", "해야 해", "하자"],
        "ja": ["べきだ", "べき", "なければならない"],
        "zh": ["应该", "必须", "要把"],
        "fa": ["باید"],
        "ar": ["يجب", "لابد", "ينبغي"],
        "uz": ["kerak", "lozim", "shart"],
        "kk": ["керек", "тиіс"],
        "ky": ["керек", "тийиш"],
        "tg": ["бояд", "лозим"],
        "tk": ["gerek", "hökman"],
        "tr": ["gerek", "lazım", "şart"],
    },
    "conditional": {
        "ru": ["если", "если бы"],
        "en": ["if", "if only"],
        "fr": ["si"], "de": ["wenn", "falls"], "es": ["si"], "it": ["se"],
        "uz": ["agar"], "kk": ["егер"], "ky": ["эгер"], "tg": ["агар"], "tk": ["eger"], "tr": ["eğer"],
        "fa": ["اگر"], "ar": ["إذا", "لو"], "zh": ["如果"], "ja": ["もし"], "ko": ["만약"],
    },
    # ---------------------------------------------------- КОНКРЕТНОСТЬ: ЦЕЛЬ
    "second_person": {
        "ru": ["тебя", "тебе", "тобой", "ты", "вас", "вам", "вами", "твой", "твою", "твоего", "твоей"],
        "en": ["you", "your", "yours"],
        "fr": ["toi", "te", "vous", "ton", "ta", "tes"],
        "de": ["dich", "dir", "euch", "du", "ihr"],
        "es": ["te", "ti", "tu", "vosotros", "ustedes"],
        "it": ["ti", "te", "vi", "voi"],
        "ko": ["너를", "너희", "당신", "네가"],
        "ja": ["お前", "てめえ", "貴様", "あなた"],
        "zh": ["你", "你们"],
        "fa": ["تو", "تورا", "شما"],
        "ar": ["أنت", "انت", "أنتم"],
        "uz": ["seni", "sizni", "sen", "senga", "sizlarni", "seni o'ldiraman"],
        "kk": ["сені", "сен", "сізді", "сендерді"],
        "ky": ["сени", "сен", "силерди", "сизди"],
        "tg": ["туро", "ту", "шуморо", "шумо"],
        "tk": ["seni", "sen", "sizi"],
        "tr": ["seni", "sen", "sizi"],
    },
    "third_person": {
        "ru": ["его", "ее", "её", "их", "ему", "ей", "им", "него", "нее", "них"],
        "en": ["him", "her", "them"],
        "fr": ["lui", "leur"],
        "de": ["ihn", "ihm", "ihnen"],
        "es": ["le", "les"],
                "ko": ["그를", "그녀를", "그들을"],
        "ja": ["あいつ", "彼を", "彼女を"],
        "zh": ["他", "她", "他们", "她们"],
        "fa": ["او را", "آنها را", "اورا"],
                "uz": ["uni", "ularni", "unga"],
        "kk": ["оны", "оларды"],
        "ky": ["аны", "аларды"],
        "tg": ["ӯро", "онҳоро"],
        "tk": ["ony", "olary"],
        "tr": ["onu", "onları"],
    },
    "mass_target": {
        "ru": ["всех", "каждого", "толпу", "людей", "всех подряд"],
        "en": ["everyone", "everybody", "all of them", "all of you", "every last", "people"],
        "fr": ["tout le monde", "tous"], "de": ["alle", "jeden"], "es": ["todos", "a todo el mundo"], "it": ["tutti"],
        "ko": ["모두", "다 죽", "전부"], "ja": ["全員", "みんな"], "zh": ["所有人", "全部", "统统"],
        "fa": ["همه را", "همهشان", "همه شان"], "ar": ["الجميع", "كلهم"],
        "uz": ["hammasini", "hammani", "barchani"], "kk": ["бәрін", "барлығын"],
        "ky": ["баарын", "бардыгын"], "tg": ["ҳамаро", "ҳамаашонро"], "tk": ["hemmesini", "hemmäni"],
        "tr": ["herkesi", "hepsini"],
    },
    "titles": {
        "ru": ["депутат*", "учител*", "директор*", "судья", "судью", "имам*", "священник*", "журналист*", "президент*", "министр*", "хоким*", "аким*", "мэр*", "полицейск*", "блогер*"],
        "en": ["teacher", "principal", "judge", "imam", "priest", "rabbi", "journalist", "president", "minister", "mayor", "officer", "blogger"],
        "fr": ["professeur", "juge", "imam", "pretre", "journaliste", "maire", "ministre"],
        "de": ["lehrer", "richter", "imam", "priester", "journalist*", "burgermeister", "minister"],
        "es": ["profesor", "juez", "imam", "sacerdote", "periodista", "alcalde", "ministro"],
        "it": ["professore", "giudice", "imam", "prete", "giornalista", "sindaco", "ministro"],
        "uz": ["o'qituvchi*", "direktor*", "sudya", "imom*", "jurnalist*", "prezident*", "vazir*", "hokim*", "bloger*"],
        "kk": ["мұғалім*", "директор*", "судья", "имам*", "журналист*", "президент*", "министр*", "әкім*", "блогер*"],
        "ky": ["мугалим*", "директор*", "судья", "имам*", "журналист*", "президент*", "министр*", "аким*", "блогер*"],
        "tg": ["муаллим*", "директор*", "судя", "имом*", "рӯзноманигор*", "президент*", "вазир*", "раис*"],
        "ko": ["선생님", "판사", "기자", "대통령", "장관", "시장님"], "ja": ["先生", "裁判官", "記者", "大統領", "大臣", "市長"],
        "zh": ["老师", "法官", "记者", "总统", "部长", "市长"], "fa": ["معلم", "قاضی", "خبرنگار", "رئیس جمهور", "وزیر"],
        "ar": ["المعلم", "القاضي", "الصحفي", "الرئيس", "الوزير", "الإمام"],
        "tk": ["mugallym*", "kazy", "žurnalist*"], "tr": ["öğretmen*", "hakim", "imam", "gazeteci*", "bakan*", "başkan*"],
    },
    # Обозначения людей по роли/ярлыку (не защищённые группы): цель есть, но это не рознь
    "role_labels": {
        "ru": ["предател*", "враг*", "изменник*", "стукач*"],
        "en": ["traitors", "traitor", "enemies", "snitches", "snitch"],
        "fr": ["traitres", "ennemis"], "de": ["verrater", "feinde"], "es": ["traidores", "enemigos"], "it": ["traditori", "nemici"],
        "uz": ["xoin*", "sotqin*", "dushman*"], "kk": ["сатқын*", "жау*"], "ky": ["чыккынчы*", "душман*"],
        "tg": ["хоин*", "душман*"], "tk": ["haýyn*", "duşman*"], "tr": ["hain*", "düşman*"],
        "fa": ["خائنان", "خائن", "دشمنان"], "ar": ["الخونة", "خائن", "الأعداء"],
        "zh": ["叛徒", "敌人"], "ja": ["裏切り者", "敵ども"], "ko": ["배신자", "적들"],
    },
    "institution": {
        "ru": ["школ*", "гимнази*", "лицей", "лицея", "лицее", "университет*", "вуз*", "колледж*", "мечет*", "церк*", "храм*", "синагог*", "рынок", "рынке", "базар*", "тц", "торгов* центр*", "метро", "вокзал*", "аэропорт*", "посольств*", "отделени* полиции", "концерт*", "стадион*", "детск* сад*", "больниц*", "военкомат*"],
        "en": ["school", "mosque", "church", "synagogue", "mall", "market", "station", "airport", "embassy", "police station", "concert", "stadium", "university", "campus", "kindergarten", "hospital"],
        "fr": ["ecole", "college", "lycee", "mosquee", "eglise", "synagogue", "centre commercial", "gare", "aeroport", "ambassade", "stade"],
        "de": ["schule", "moschee", "kirche", "synagoge", "einkaufszentrum", "bahnhof", "flughafen", "botschaft", "stadion", "universitat"],
        "es": ["escuela", "colegio", "mezquita", "iglesia", "sinagoga", "centro comercial", "estacion", "aeropuerto", "embajada", "estadio"],
        "it": ["scuola", "moschea", "chiesa", "sinagoga", "centro commerciale", "stazione", "aeroporto", "ambasciata", "stadio"],
        "ko": ["학교", "모스크", "교회", "성당", "시장", "쇼핑몰", "공항", "대사관", "지하철역"],
        "ja": ["学校", "モスク", "教会", "駅", "空港", "大使館", "ショッピングモール"],
        "zh": ["学校", "清真寺", "教堂", "商场", "车站", "机场", "大使馆", "地铁", "校门"],
        "fa": ["مدرسه", "مسجد", "کلیسا", "بازار", "مرکز خرید", "ایستگاه", "فرودگاه", "سفارت"],
        "ar": ["مدرسة", "مسجد", "كنيسة", "سوق", "مركز تجاري", "محطة", "مطار", "سفارة"],
        "uz": ["maktab*", "litsey*", "universitet*", "masjid*", "cherkov*", "bozor*", "savdo markaz*", "metro", "vokzal*", "aeroport*", "elchixona*", "stadion*", "kollej*"],
        "kk": ["мектеп*", "мешіт*", "шіркеу*", "базар*", "сауда орталығ*", "әуежай*", "вокзал*", "университет*", "стадион*"],
        "ky": ["мектеп*", "мечит*", "чиркөө*", "базар*", "соода борбор*", "аэропорт*", "вокзал*", "университет*", "стадион*"],
        "tg": ["мактаб*", "масҷид*", "калисо*", "бозор*", "маркази савдо", "фурудгоҳ*", "вокзал*", "донишгоҳ*", "стадион*"],
        "tk": ["mekdep*", "metjit*", "bazar*", "söwda merkez*", "howa menzil*", "wokzal*", "uniwersitet*"],
        "tr": ["okul*", "cami*", "kilise*", "sinagog*", "çarşı*", "alışveriş merkez*", "avm", "istasyon*", "havaliman*", "büyükelçilik*", "stadyum*"],
    },
    # ------------------------------------------------- КОНКРЕТНОСТЬ: ВРЕМЯ И МЕСТО
    "time": {
        "ru": ["сегодня", "завтра", "послезавтра", "сейчас", "в понедельник", "во вторник", "в среду", "в четверг", "в пятницу", "в субботу", "в воскресенье", "на этой неделе", "на выходных", "в эти выходные", "ночью", "утром", "вечером", "re:\\bв\\s+\\d{1,2}[:.]\\d{2}\\b", "re:\\b\\d{1,2}:\\d{2}\\b", "re:\\bв\\s+\\d{1,2}\\s+(?:утра|вечера|часов|часа|ночи)\\b", "re:\\b(?:0?[1-9]|[12]\\d|3[01])\\.(?:0[1-9]|1[0-2])(?:\\.\\d{2,4})?\\b(?![.,]\\d)", "re:\\bчерез\\s+(?:час|два|три|\\d+|неделю|день)"],
        "en": ["today", "tonight", "tomorrow", "this week", "this weekend", "next week", "on monday", "on tuesday", "on wednesday", "on thursday", "on friday", "on saturday", "on sunday", "friday", "saturday", "re:\\bat\\s+\\d{1,2}(?::\\d{2})?\\s*(?:am|pm)?\\b", "re:\\bin\\s+\\d+\\s+(?:hours|days|minutes)\\b"],
        "fr": ["aujourd'hui", "ce soir", "demain", "lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche", "re:\\ba\\s+\\d{1,2}h"],
        "de": ["heute", "morgen", "ubermorgen", "heute nacht", "montag", "dienstag", "mittwoch", "donnerstag", "freitag", "samstag", "sonntag", "re:\\bum\\s+\\d{1,2}(?::\\d{2})?\\s*uhr"],
        "es": ["hoy", "manana", "esta noche", "lunes", "martes", "miercoles", "jueves", "viernes", "sabado", "domingo", "re:\\ba las\\s+\\d{1,2}"],
        "it": ["oggi", "domani", "stasera", "lunedi", "martedi", "mercoledi", "giovedi", "venerdi", "sabato", "domenica", "re:\\balle\\s+\\d{1,2}"],
        "ko": ["오늘", "내일", "모레", "월요일", "화요일", "수요일", "목요일", "금요일", "토요일", "일요일", "re:\\d{1,2}시"],
        "ja": ["今日", "明日", "明後日", "今夜", "月曜", "火曜", "水曜", "木曜", "金曜", "土曜", "日曜", "re:\\d{1,2}時"],
        "zh": ["今天", "明天", "后天", "今晚", "周一", "周二", "周三", "周四", "周五", "周六", "周日", "星期", "re:\\d{1,2}点"],
        "fa": ["امروز", "فردا", "پسفردا", "امشب", "شنبه", "یکشنبه", "دوشنبه", "سهشنبه", "چهارشنبه", "پنجشنبه", "جمعه", "ساعت"],
        "ar": ["اليوم", "غدا", "الليلة", "الجمعة", "السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الساعة"],
        "uz": ["bugun", "ertaga", "indinga", "dushanba", "seshanba", "chorshanba", "payshanba", "juma", "jumada", "shanba", "yakshanba", "kechqurun", "ertalab", "re:\\bsoat\\s+\\d{1,2}"],
        "kk": ["бүгін", "ертең", "бүрсігүні", "дүйсенбі", "сейсенбі", "сәрсенбі", "бейсенбі", "жұма", "сенбі", "жексенбі", "кешке", "таңертең", "re:\\bсағат\\s+\\d{1,2}"],
        "ky": ["бүгүн", "эртең", "бүрсүгүнү", "дүйшөмбү", "шейшемби", "шаршемби", "бейшемби", "жума", "ишемби", "жекшемби", "кечинде", "эртең менен", "re:\\bсаат\\s+\\d{1,2}"],
        "tg": ["имрӯз", "фардо", "пагоҳ", "душанбе", "сешанбе", "чоршанбе", "панҷшанбе", "ҷумъа", "шанбе", "якшанбе", "бегоҳ", "re:\\bсоати\\s+\\d{1,2}"],
        "tk": ["şu gün", "ertir", "duşenbe", "sişenbe", "çarşenbe", "penşenbe", "anna", "şenbe", "ýekşenbe", "re:\\bsagat\\s+\\d{1,2}"],
        "tr": ["bugün", "yarın", "pazartesi", "salı", "çarşamba", "perşembe", "cuma", "cumartesi", "re:\\bsaat\\s+\\d{1,2}"],
    },
    "place": {
        "ru": ["re:\\bул\\.?\\s", "улиц*", "проспект*", "площад*", "у дома", "возле дома", "у подъезда", "во дворе", "у входа", "на остановке", "re:\\bдом\\s*№?\\s*\\d+", "re:№\\s*\\d+"],
        "en": ["street", "avenue", "square", "outside the", "in front of", "near the", "at the entrance", "re:\\bno\\.?\\s*\\d+\\b"],
        "fr": ["rue", "avenue", "place", "devant", "pres de"],
        "de": ["strasse", "platz", "vor dem", "vor der", "in der nahe"],
        "es": ["calle", "avenida", "plaza", "frente a", "cerca de"],
        "it": ["via", "piazza", "davanti", "vicino"],
        "ko": ["거리", "광장", "앞에서", "입구"],
        "ja": ["通り", "広場", "前で", "入口"],
        "zh": ["街", "广场", "门口", "附近"],
        "fa": ["خیابان", "میدان", "جلوی", "نزدیک"],
        "ar": ["شارع", "ميدان", "ساحة", "أمام", "قرب"],
        "uz": ["ko'chasi", "ko'chada", "maydon*", "uyi oldida", "yonida", "kirish joyida"],
        "kk": ["көшесі", "көшеде", "алаң*", "үйінің алдында", "жанында"],
        "ky": ["көчөсү", "көчөдө", "аянт*", "үйүнүн алдында", "жанында"],
        "tg": ["кӯчаи", "майдон*", "назди", "дар назди", "хонаат", "хонааш"],
        "tk": ["köçesi", "meýdan*", "öýüniň öňünde", "ýanynda"],
        "tr": ["sokak", "cadde*", "meydan*", "önünde", "yanında"],
    },
    # -------------------------------------------- ПРИЗНАКИ ПОДГОТОВКИ (в тексте)
    "preparation": {
        "ru": ["уже купил", "уже купила", "купил патроны", "купил ружье", "купил ружьё", "достал ствол", "достал оружие", "все готово", "всё готово", "план готов", "уже готов", "подготовил*", "собрал бомбу", "собрал устройство", "изготовил*", "разведал*", "приготовил*", "схема готова", "маршрут выбран"],
        "en": ["already have the", "already bought", "bought a gun", "bought a rifle", "bought ammo", "got a gun", "have the rifle", "everything is ready", "plan is ready", "i'm ready", "im ready", "prepared", "built a bomb", "made the device", "scouted"],
        "fr": ["j'ai achete une arme", "tout est pret", "je suis pret", "le plan est pret"],
        "de": ["habe eine waffe gekauft", "alles ist bereit", "ich bin bereit", "der plan steht"],
        "es": ["compre un arma", "todo esta listo", "estoy listo", "el plan esta listo"],
        "it": ["ho comprato una pistola", "tutto e pronto", "sono pronto", "il piano e pronto"],
        "ko": ["준비됐다", "준비는 끝났다", "총을 샀다", "계획은 다 짰다"],
        "ja": ["準備はできている", "準備できた", "銃を買った", "計画は整った"],
        "zh": ["准备好了", "已经准备", "买了枪", "计划好了"],
        "fa": ["آمادهام", "همه چیز آماده است", "اسلحه خریدم", "نقشه آماده است"],
        "ar": ["جاهز", "كل شيء جاهز", "اشتريت سلاحا", "الخطة جاهزة"],
        "uz": ["qurol sotib oldim", "tayyorman", "reja tayyor", "hammasi tayyor"],
        "kk": ["дайынмын", "жоспар дайын", "қару сатып алдым", "бәрі дайын"],
        "ky": ["даярмын", "план даяр", "курал сатып алдым", "баары даяр"],
        "tg": ["тайёрам", "нақша тайёр", "силоҳ харидам", "ҳама тайёр"],
        "tk": ["taýýar", "meýilnama taýýar", "ýarag satyn aldym"],
        "tr": ["hazırım", "plan hazır", "silah aldım", "her şey hazır"],
    },
    # -------------------------------------------- ГРУППЫ (нац., рел., соц.)
    "groups": {
        "ru": ["re:\\bрусск(?:ие|их|им|ими)\\b", "re:\\bузбек(?:и|ов|ам|ами)\\b", "re:\\bтаджик(?:и|ов|ам|ами)\\b", "re:\\bказах(?:и|ов|ам|ами)\\b", "re:\\b(?:киргиз|кыргыз)(?:ы|ов|ам|ами)\\b", "re:\\bтуркмен(?:ы|ов|ам|ами)\\b", "re:\\bевре(?:и|ев|ям|ями)\\b", "re:\\bармян(?:е|ам|ами)?\\b", "re:\\bазербайджанц(?:ы|ев|ам)\\b", "re:\\bчеченц(?:ы|ев|ам)\\b", "re:\\bуйгур(?:ы|ов|ам)\\b", "re:\\bкорейц(?:ы|ев|ам)\\b", "re:\\bкитайц(?:ы|ев|ам)\\b", "re:\\bукраинц(?:ы|ев|ам)\\b", "re:\\bмусульман(?:е|ам|ами)?\\b", "re:\\bхристиан(?:е|ам|ами)?\\b", "re:\\bправославн(?:ые|ых|ым)\\b", "re:\\bиуде(?:и|ев|ям)\\b", "re:\\bшиит(?:ы|ов|ам)\\b", "re:\\bсуннит(?:ы|ов|ам)\\b", "re:\\bатеист(?:ы|ов|ам)\\b", "мигрант*", "приезжие", "приезжих", "приезжим", "гастарбайтер*", "неверные", "неверных", "неверным", "кафир*", "лгбт*"],
        "en": ["russians", "uzbeks", "tajiks", "kazakhs", "kyrgyz", "jews", "muslims", "christians", "shia", "sunni*", "migrants", "immigrants", "refugees", "infidels", "kafirs", "atheists"],
        "fr": ["juifs", "musulmans", "chretiens", "migrants", "immigres", "etrangers", "infideles"],
        "de": ["juden", "muslime", "christen", "migranten", "auslander", "fluchtlinge", "unglaubige"],
        "es": ["judios", "musulmanes", "cristianos", "migrantes", "inmigrantes", "extranjeros", "infieles"],
        "it": ["ebrei", "musulmani", "cristiani", "migranti", "immigrati", "stranieri", "infedeli"],
        "ko": ["유대인", "무슬림", "이슬람교도", "기독교인", "이민자", "외국인", "난민"],
        "ja": ["ユダヤ人", "イスラム教徒", "ムスリム", "キリスト教徒", "移民", "外国人", "難民"],
        "zh": ["犹太人", "穆斯林", "基督徒", "移民", "外国人", "难民", "异教徒"],
        "fa": ["یهودیان", "مسلمانان", "مسیحیان", "بهاییان", "افغانها", "مهاجران", "کافران", "سنیها", "شیعیان"],
        "ar": ["اليهود", "المسلمين", "المسيحيين", "النصارى", "الكفار", "الشيعة", "السنة", "المهاجرين", "اللاجئين"],
        "uz": ["ruslar*", "o'zbeklar*", "tojiklar*", "qozoqlar*", "qirg'izlar*", "yahudiylar*", "musulmonlar*", "xristianlar*", "kofirlar*", "shialar*", "muhojirlar*"],
        "kk": ["орыстар*", "өзбектер*", "тәжіктер*", "қазақтар*", "қырғыздар*", "еврейлер*", "мұсылмандар*", "христиандар*", "кәпірлер*", "мигранттар*"],
        "ky": ["орустар*", "өзбектер*", "тажиктер*", "казактар*", "кыргыздар*", "жөөттөр*", "мусулмандар*", "христиандар*", "каапырлар*", "мигранттар*"],
        "tg": ["русҳо", "ӯзбекҳо", "тоҷикон", "қазоқҳо", "қирғизҳо", "яҳудиён", "мусулмонон", "насрониён", "кофирон"],
        "tk": ["ruslar*", "özbekler*", "täjikler*", "gazaklar*", "gyrgyzlar*", "ýehudylar*", "musulmanlar*", "hristianlar*", "kapyrlar*"],
        "tr": ["ruslar*", "özbekler*", "yahudiler*", "müslümanlar*", "hristiyanlar*", "kafirler*", "göçmenler*", "mülteciler*", "aleviler*"],
    },
    # ---------------------------------------- ИДИОМЫ (насильственная лексика не буквально)
    "idioms": {
        "ru": ["убить время", "убиваю время", "убил время", "убила взглядом", "убил взглядом", "убийственно", "убийственн*", "взорвал танцпол", "взорвала танцпол", "взорвать интернет", "взорвал интернет", "взорвал мозг", "мозг взорван", "это бомба", "бомбит", "бомбическ*", "умираю со смеху", "убил на это", "убила на это", "застрелиться можно", "разнесем их", "разнесём их", "порвем их", "порвём их"],
        "en": ["kill time", "killing time", "killing it", "killed it", "kill for a", "dressed to kill", "bomb the exam", "bombed the test", "bombed the exam", "blew up online", "blow up my phone", "shoot me a message", "shoot a video", "photo shoot", "shoot for the stars", "dying of laughter", "i'm dead", "slay", "killer app"],
        "fr": ["tuer le temps", "mort de rire"],
        "de": ["zeit totschlagen", "totlachen"],
        "es": ["matarse estudiando", "me voy a matar estudiando", "me muero de risa", "me mata de risa", "matar el tiempo"],
        "it": ["ammazzare il tempo", "morire dal ridere"],
        "ko": ["죽겠다", "웃겨 죽"],
        "ja": ["死ぬほど", "笑い死"],
        "zh": ["笑死", "打发时间"],
        "fa": ["وقت کشی"],
        "ar": ["قتل الوقت"],
        "uz": ["vaqt o'ldirish", "imtihonni portlataman"],
        "kk": ["емтиханды жарып жіберемін", "емтиханды жарып", "уақыт өлтіру", "сахнаны жарып"],
        "ky": ["убакыт өлтүрүү", "сахнаны жардыр*"],
        "tg": ["вақт куштан"],
        "tr": ["vakit öldürmek", "gülmekten öldüm"],
    },
}

# Отрицания перед словом (окно из нескольких токенов)
NEGATORS: dict[str, set[str]] = {
    "ru": {"не", "ни", "никогда", "нельзя", "незачем"},
    "en": {"not", "never", "don't", "dont", "won't", "wont", "wouldn't", "no", "cannot", "can't", "cant", "shouldn't", "mustn't", "didn't"},
    "fr": {"ne", "n'", "pas", "jamais"},
    "de": {"nicht", "nie", "niemals", "kein", "keine"},
    "es": {"no", "nunca", "jamas"},
    "it": {"non", "mai"},
    "uz": {"emas", "hech", "yo'q"},
    "kk": {"емес", "ешқашан"},
    "ky": {"эмес", "эч качан"},
    "tg": {"не", "ҳеҷ", "ҳаргиз"},
    "tk": {"däl", "hiç"},
    "tr": {"değil", "asla", "hiç"},
    "ar": {"لا", "لن", "لم", "ما"},
    "ko": {"안", "못"},
}
